# https://periodictable.com/index.html
LATTICES = {
    "BCC": ("Body Centered Cubic", "https://en.wikipedia.org/wiki/Body_centered_cubic"),
    "FCC": ("Face Centered Cubic", "https://en.wikipedia.org/wiki/Face_centered_cubic"),
    "HCP": ("Hexagonal Close Packed", "https://en.wikipedia.org/wiki/Hexagonal_close_packed"),
    "ORC": ("Orthorhombic", "https://en.wikipedia.org/wiki/Orthorhombic"),
    "TET": ("Tetragonal", "https://en.wikipedia.org/wiki/Tetragonal"),
    "RHL": ("Rhombohedral", "https://en.wikipedia.org/wiki/Trigonal"),
    "HEX": ("Hexagonal", "https://en.wikipedia.org/wiki/Hexagonal_crystal_system"),
    "CUB": ("Simple Cubic", "https://en.wikipedia.org/wiki/Cubic_crystal_system"),
    "SC": ("Simple Cubic", "https://en.wikipedia.org/wiki/Cubic_crystal_system"),
    "DIA": ("Diamond Cubic", "https://en.wikipedia.org/wiki/Diamond_cubic"),
    "MCL": ("Monoclinic", "https://en.wikipedia.org/wiki/Monoclinic"),
}

IMAGES = {
    "Actinium": {"image": "https://periodictable.com/Samples/089.4/s9s.JPG"},
    "Aluminum": {"image": "https://periodictable.com/Samples/013.21/s9s.JPG"},
    "Americium": {"image": "https://periodictable.com/Samples/095.1/s9s.JPG"},
    "Antimony": {"image": "https://periodictable.com/Samples/051.15/s9s.JPG"},
    "Argon": {"image": "https://periodictable.com/Samples/018.7/s9s.JPG"},
    "Arsenic": {"image": "https://periodictable.com/Samples/033.7/s9s.JPG"},
    "Astatine": {"image": "https://periodictable.com/Samples/085.4/s9s.JPG"},
    "Barium": {"image": "https://periodictable.com/Samples/056.1/s9s.JPG"},
    "Berkelium": {"image": "https://periodictable.com/Samples/097.2/s9s.JPG"},
    "Beryllium": {"image": "https://periodictable.com/Samples/004.1/s9s.JPG"},
    "Bismuth": {"image": "https://periodictable.com/Samples/083.23/s9s.JPG"},
    "Bohrium": {"image": "https://periodictable.com/Samples/107.2/s9s.JPG"},
    "Boron": {"image": "https://periodictable.com/Samples/005.6/s9s.JPG"},
    "Bromine": {"image": "https://periodictable.com/Samples/035.2/s9s.JPG"},
    "Cadmium": {"image": "https://periodictable.com/Samples/048.11/s9s.JPG"},
    "Calcium": {"image": "https://periodictable.com/Samples/020.6/s9s.JPG"},
    "Californium": {"image": "https://periodictable.com/Samples/098.2/s9s.JPG"},
    "Carbon": {"image": "https://periodictable.com/Samples/006.x4/s9s.JPG"},
    "Cerium": {"image": "https://periodictable.com/Samples/058.7/s9s.JPG"},
    "Cesium": {"image": "https://periodictable.com/Samples/055.4/s9s.JPG"},
    "Chlorine": {"image": "https://periodictable.com/Samples/017.3/s9s.JPG"},
    "Chromium": {"image": "https://periodictable.com/Samples/024.11/s9s.JPG"},
    "Cobalt": {"image": "https://periodictable.com/Samples/027.14/s9s.JPG"},
    "Copernicium": {"image": "https://periodictable.com/Samples/112.1/s9s.JPG"},
    "Copper": {"image": "https://periodictable.com/Samples/029.24/s9s.JPG"},
    "Curium": {"image": "https://periodictable.com/Samples/096.2/s9s.JPG"},
    "Darmstadtium": {"image": "https://periodictable.com/Samples/110.1/s9s.JPG"},
    "Dubnium": {"image": "https://periodictable.com/Samples/105.2/s9s.JPG"},
    "Dysprosium": {"image": "https://periodictable.com/Samples/066.2/s9s.JPG"},
    "Einsteinium": {"image": "https://periodictable.com/Samples/099.3/s9s.JPG"},
    "Erbium": {"image": "https://periodictable.com/Samples/068.5/s9s.JPG"},
    "Europium": {"image": "https://periodictable.com/Samples/063.9/s9s.JPG"},
    "Fermium": {"image": "https://periodictable.com/Samples/100.3/s9s.JPG"},
    "Flerovium": {"image": "https://periodictable.com/Samples/114.1/s9s.JPG"},
    "Fluorine": {"image": "https://periodictable.com/Samples/009.6/s9s.JPG"},
    "Francium": {"image": "https://periodictable.com/Samples/087.4/s9s.JPG"},
    "Gadolinium": {"image": "https://periodictable.com/Samples/064.1/s9s.JPG"},
    "Gallium": {"image": "https://periodictable.com/Samples/031.7/s9s.JPG"},
    "Germanium": {"image": "https://periodictable.com/Samples/032.10/s9s.JPG"},
    "Gold": {"image": "https://periodictable.com/Samples/079.2/s9s.JPG"},
    "Hafnium": {"image": "https://periodictable.com/Samples/072.2/s9s.JPG"},
    "Hassium": {"image": "https://periodictable.com/Samples/108.2/s9s.JPG"},
    "Helium": {"image": "https://periodictable.com/Samples/002.6/s9s.JPG"},
    "Holmium": {"image": "https://periodictable.com/Samples/067.4/s9s.JPG"},
    "Hydrogen": {"image": "https://periodictable.com/Samples/001.x3/s9s.JPG"},
    "Indium": {"image": "https://periodictable.com/Samples/049.7/s9s.JPG"},
    "Iodine": {"image": "https://periodictable.com/Samples/053.8/s9s.JPG"},
    "Iridium": {"image": "https://periodictable.com/Samples/077.4/s9s.JPG"},
    "Iron": {"image": "https://periodictable.com/Samples/026.32/s9s.JPG"},
    "Krypton": {"image": "https://periodictable.com/Samples/036.6/s9s.JPG"},
    "Lanthanum": {"image": "https://periodictable.com/Samples/057.1/s9s.JPG"},
    "Lawrencium": {"image": "https://periodictable.com/Samples/103.2/s9s.JPG"},
    "Lead": {"image": "https://periodictable.com/Samples/082.27/s9s.JPG"},
    "Lithium": {"image": "https://periodictable.com/Samples/003.3/s9s.JPG"},
    "Livermorium": {"image": "https://periodictable.com/Samples/116.1/s9s.JPG"},
    "Lutetium": {"image": "https://periodictable.com/Samples/071.3/s9s.JPG"},
    "Magnesium": {"image": "https://periodictable.com/Samples/012.15/s9s.JPG"},
    "Manganese": {"image": "https://periodictable.com/Samples/025.7/s9s.JPG"},
    "Meitnerium": {"image": "https://periodictable.com/Samples/109.1/s9s.JPG"},
    "Mendelevium": {"image": "https://periodictable.com/Samples/101.3/s9s.JPG"},
    "Mercury": {"image": "https://periodictable.com/Samples/080.14/s9s.JPG"},
    "Molybdenum": {"image": "https://periodictable.com/Samples/042.2/s9s.JPG"},
    "Moscovium": {"image": "https://periodictable.com/Samples/115.1/s9s.JPG"},
    "Neodymium": {"image": "https://periodictable.com/Samples/060.2/s9s.JPG"},
    "Neon": {"image": "https://periodictable.com/Samples/010.8/s9s.JPG"},
    "Neptunium": {"image": "https://periodictable.com/Samples/093.2/s9s.JPG"},
    "Nickel": {"image": "https://periodictable.com/Samples/028.9/s9s.JPG"},
    "Nihonium": {"image": "https://periodictable.com/Samples/113.1/s9s.JPG"},
    "Niobium": {"image": "https://periodictable.com/Samples/041.13/s9s.JPG"},
    "Nitrogen": {"image": "https://periodictable.com/Samples/007.8/s9s.JPG"},
    "Nobelium": {"image": "https://periodictable.com/Samples/102.2/s9s.JPG"},
    "Oganesson": {"image": "https://periodictable.com/Samples/118.1/s12s.JPG"},
    "Osmium": {"image": "https://periodictable.com/Samples/076.8/s9s.JPG"},
    "Oxygen": {"image": "https://periodictable.com/Samples/008.10/s9s.JPG"},
    "Palladium": {"image": "https://periodictable.com/Samples/046.10/s9s.JPG"},
    "Phosphorus": {"image": "https://periodictable.com/Samples/015.6/s9s.JPG"},
    "Platinum": {"image": "https://periodictable.com/Samples/078.6/s9s.JPG"},
    "Plutonium": {"image": "https://periodictable.com/Samples/094.3/s9s.JPG"},
    "Polonium": {"image": "https://periodictable.com/Samples/084.8/s9s.JPG"},
    "Potassium": {"image": "https://periodictable.com/Samples/019.6/s9s.JPG"},
    "Praseodymium": {"image": "https://periodictable.com/Samples/059.1/s9s.JPG"},
    "Promethium": {"image": "https://periodictable.com/Samples/061.1/s9s.JPG"},
    "Protactinium": {"image": "https://periodictable.com/Samples/091.5/s9s.JPG"},
    "Radium": {"image": "https://periodictable.com/Samples/088.15/s9s.JPG"},
    "Radon": {"image": "https://periodictable.com/Samples/086.4/s9s.JPG"},
    "Rhenium": {"image": "https://periodictable.com/Samples/075.10/s9s.JPG"},
    "Rhodium": {"image": "https://periodictable.com/Samples/045.7/s9s.JPG"},
    "Roentgenium": {"image": "https://periodictable.com/Samples/111.1/s9s.JPG"},
    "Rubidium": {"image": "https://periodictable.com/Samples/037.5/s9s.JPG"},
    "Ruthenium": {"image": "https://periodictable.com/Samples/044.5/s9s.JPG"},
    "Rutherfordium": {"image": "https://periodictable.com/Samples/104.2/s9s.JPG"},
    "Samarium": {"image": "https://periodictable.com/Samples/062.6/s9s.JPG"},
    "Scandium": {"image": "https://periodictable.com/Samples/021.8/s9s.JPG"},
    "Seaborgium": {"image": "https://periodictable.com/Samples/106.4/s9s.JPG"},
    "Selenium": {"image": "https://periodictable.com/Samples/034.12/s9s.JPG"},
    "Silicon": {"image": "https://periodictable.com/Samples/014.12/s9s.JPG"},
    "Silver": {"image": "https://periodictable.com/Samples/047.26/s9s.JPG"},
    "Sodium": {"image": "https://periodictable.com/Samples/011.9/s9s.JPG"},
    "Strontium": {"image": "https://periodictable.com/Samples/038.5/s9s.JPG"},
    "Sulfur": {"image": "https://periodictable.com/Samples/NativeSulfur/s9s.JPG"},
    "Tantalum": {"image": "https://periodictable.com/Samples/073.8/s9s.JPG"},
    "Technetium": {"image": "https://periodictable.com/Samples/043.1/s9s.JPG"},
    "Tellurium": {"image": "https://periodictable.com/Samples/052.4/s9s.JPG"},
    "Tennessine": {"image": "https://periodictable.com/Samples/117.1/s9s.JPG"},
    "Terbium": {"image": "https://periodictable.com/Samples/065.5/s9s.JPG"},
    "Thallium": {"image": "https://periodictable.com/Samples/081.5/s9s.JPG"},
    "Thorium": {"image": "https://periodictable.com/Samples/090.6/s9s.JPG"},
    "Thulium": {"image": "https://periodictable.com/Samples/069.1/s9s.JPG"},
    "Tin": {"image": "https://periodictable.com/Samples/050.22/s9s.JPG"},
    "Titanium": {"image": "https://periodictable.com/Samples/022.18/s9s.JPG"},
    "Tungsten": {"image": "https://periodictable.com/Samples/074.5/s9s.JPG"},
    "Uranium": {"image": "https://periodictable.com/Samples/092.19/s9s.JPG"},
    "Vanadium": {"image": "https://periodictable.com/Samples/023.10/s9s.JPG"},
    "Xenon": {"image": "https://periodictable.com/Samples/054.6/s9s.JPG"},
    "Ytterbium": {"image": "https://periodictable.com/Samples/070.3/s9s.JPG"},
    "Yttrium": {"image": "https://periodictable.com/Samples/039.11/s9s.JPG"},
    "Zinc": {"image": "https://periodictable.com/Samples/030.7/s9s.JPG"},
    "Zirconium": {"image": "https://periodictable.com/Samples/040.17/s9s.JPG"},
}

UNITS = {
    "abundance_crust": {"name": "Abundance in the crust", "units": "mg/kg"},
    "abundance_sea": {"name": "Abundance in the sea", "units": "mg/L"},
    "annotation": {"name": "Annotations", "units": ""},
    "atomic_number": {"name": "Atomic number", "units": ""},
    "atomic_radius": {"name": "Atomic radius", "units": "pm"},
    "atomic_radius_rahm": {"name": "Atomic radius by Rahm et al.", "units": "pm"},
    "atomic_volume": {"name": "Atomic volume", "units": "cm³/mol"},
    "atomic_weight": {"name": "Atomic weight", "units": ""},
    "atomic_weight_uncertainty": {"name": "Atomic weight uncertainty", "units": ""},
    "block": {"name": "Block in periodic table", "units": ""},
    "boiling_point": {"name": "Boiling temperature", "units": "K"},
    "c6": {"name": "C_6 dispersion coefficient", "units": "a.u."},
    "c6_gb": {"name": "C_6 dispersion coefficient in a.u. (Gould & Bučko)", "units": "a.u."},
    "cas": {"name": "Chemical Abstract Service identifier", "units": ""},
    "covalent_radius_bragg": {"name": "Covalent radius by Bragg", "units": "pm"},
    "covalent_radius_cordero": {"name": "Covalent radius by Cerdero et al.", "units": "pm"},
    "covalent_radius_pyykko": {"name": "Covalent radius by Pyykko et al.", "units": "pm"},
    "covalent_radius_pyykko_double": {"name": "Covalent radius by Pyykko et al.", "units": "pm"},
    "covalent_radius_pyykko_triple": {"name": "Covalent radius by Pyykko et al.", "units": "pm"},
    "covalent_radius_slater": {"name": "Covalent radius by Slater", "units": "pm"},
    "cpk_color": {"name": "Element colour in CPK convention", "units": ""},
    "density": {"name": "Density at 295K", "units": "g/cm³"},
    "description": {"name": "Description", "units": ""},
    "dipole_polarizability": {"name": "Dipole polarizability", "units": "a.u."},
    "discoverers": {"name": "Discoverers of the Element", "units": ""},
    "discovery_location": {"name": "Discovery Location", "units": ""},
    "dipole_year": {"name": "Year the element was discovered", "units": ""},
    "electron_affinity": {"name": "Electron affinity", "units": "eV"},
    "electrons": {"name": "Number of electrons", "units": ""},
    "en_allen": {"name": "Allen's scale of electronegativity", "units": "eV"},
    "en_ghosh": {"name": "Ghosh's scale of electronegativity", "units": ""},
    "en_mulliken": {"name": "Mulliken's scale of electronegativity", "units": "eV"},
    "en_pauling": {"name": "Pauling's scale of electronegativity", "units": ""},
    "econf": {"name": "Ground state electro configuration", "units": ""},
    "evaporation_heat": {"name": "Evaporation heat", "units": "kJ/mol"},
    "fusion_heat": {"name": "Fusion heat", "units": "KJ/mol"},
    "gas_basicity": {"name": "Gas bacisity", "units": "KJ/mol"},
    "geochemical_class": {"name": "Geochemical class", "units": ""},
    "goldschmidt_class": {"name": "Goldschmidt class", "units": ""},
    "group": {"name": "Group", "units": ""},
    "heat_of_formation": {"name": "Heat of formation", "units": "kJ/mol"},
    "ionenergy": {"name": "Ionization energies", "units": "eV"},
    "ionic_radii": {"name": "Ionic and crystal radii", "units": "pm"},
    "is_monoisotopic": {"name": "Is monoisotopic", "units": ""},
    "is_radioactive": {"name": "Is radioactive", "units": ""},
    "isotopes": {"name": "Isotopes", "units": ""},
    "jmol_color": {"name": "Colour in Jmol convention", "units": ""},
    "lattice_constant": {"name": "Lattice constant", "units": "Angstrom"},
    "lattice_structure": {"name": "Lattice structure", "units": ""},
    "mass_number": {"name": "Mass number", "units": ""},
    "melting_point": {"name": "Melting temperature", "units": "K"},
    "mendeleev_number": {"name": "Mendeleev number", "units": ""},
    "metallic_radius": {"name": "Single-bond metallic radius", "units": "pm"},
    "metallic_radius_c12": {"name": "Metallic radius with 12 nearest neighbors", "units": "pm"},
    "molcas_gv_color": {"name": "Colour in MOLCAS GV convention", "units": ""},
    "name": {"name": "Name", "units": ""},
    "name_origin": {"name": "Name Origin", "units": ""},
    "neutrons": {"name": "Number of neutrons", "units": ""},
    "oxistates": {"name": "Oxidation states", "units": ""},
    "period": {"name": "Period", "units": ""},
    "proton_affinity": {"name": "Proton affinity", "units": "KJ/mol"},
    "protons": {"name": "Number of protons", "units": ""},
    "sconst": {"name": "Nuclear charge screening constants", "units": ""},
    "series": {"name": "Index to chemical series", "units": ""},
    "sources": {"name": "Sources", "units": ""},
    "specific_heat": {"name": "Specific heat at 20 C", "units": "J/(g mol)"},
    "symbol": {"name": "Symbol", "units": ""},
    "thermal_conductivity": {"name": "Thermal conductivity at 25 C", "units": "W/(m K)"},
    "uses": {"name": "Uses", "units": ""},
    "vdw_radius": {"name": "Van der Waals radius", "units": "pm"},
    "vdw_radius_alvarez": {"name": "Van der Waals radius according to Alvarez", "units": "pm"},
    "vdw_radius_batsanov": {"name": "Van der Waals radius according to Batsanov", "units": "pm"},
    "vdw_radius_bondi": {"name": "Van der Waals radius according to Bondi", "units": "pm"},
    "vdw_radius_dreiding": {"name": "Van der Waals radius from the DREIDING FF", "units": "pm"},
    "vdw_radius_mm3": {"name": "Van der Waals radius from the MM3 FF", "units": "pm"},
    "vdw_radius_rt": {
        "name": "Van der Waals radius according to Rowland and Taylor",
        "units": "pm",
    },
    "vdw_radius_truhlar": {"name": "Van der Waals radius according to Truhlar", "units": "pm"},
    "vdw_radius_uff": {"name": "Van der Waals radius from the UFF", "units": "pm"},
    "xrf": {"name": "X-Ray Fluorescence", "units": "nm"},
}
