card_list: dict = {
    "1": {
        "card_meaning": "Inspiration, power, creation, beginnings, potential",
        "card_name": "Ace of Wands",
        "card_url": "https://tarot.com/tarot/ace-of-wands/",
        "card_img": "http://i.imgur.com/MfJ1s77.jpg",
        "rank": "ace",
        "suit": "wands",
        "arcana": "minor",
    },
    "2": {
        "card_meaning": "Future planning, progress, decisions, discovery",
        "card_name": "Two of Wands",
        "card_url": "https://tarot.com/tarot/two-of-wands/",
        "card_img": "http://i.imgur.com/Ghb63pd.jpg",
        "rank": "two",
        "suit": "wands",
        "arcana": "minor",
    },
    "3": {
        "card_meaning": "Preparation, foresight, enterprise, expansion",
        "card_name": "Three of Wands",
        "card_url": "https://tarot.com/tarot/three-of-wands/",
        "card_img": "http://i.imgur.com/NIUAuzw.jpg",
        "rank": "three",
        "suit": "wands",
        "arcana": "minor",
    },
    "4": {
        "card_meaning": "Celebration, harmony, marriage, home, community",
        "card_name": "Four of Wands",
        "card_url": "https://tarot.com/tarot/four-of-wands/",
        "card_img": "http://i.imgur.com/heelDVY.jpg",
        "rank": "four",
        "suit": "wands",
        "arcana": "minor",
    },
    "5": {
        "card_meaning": "Disagreement, competition, strife, tension, conflict",
        "card_name": "Five of Wands",
        "card_url": "https://tarot.com/tarot/five-of-wands/",
        "card_img": "http://i.imgur.com/Qojm2p1.jpg",
        "rank": "five",
        "suit": "wands",
        "arcana": "minor",
    },
    "6": {
        "card_meaning": "Public recognition, victory, progress, self-confidence",
        "card_name": "Six of Wands",
        "card_url": "https://tarot.com/tarot/six-of-wands/",
        "card_img": "http://i.imgur.com/DClClQ5.jpg",
        "rank": "six",
        "suit": "wands",
        "arcana": "minor",
    },
    "7": {
        "card_meaning": "Challenge, competition, perseverance",
        "card_name": "Seven of Wands",
        "card_url": "https://tarot.com/tarot/seven-of-wands/",
        "card_img": "http://i.imgur.com/hsNtHC0.jpg",
        "rank": "seven",
        "suit": "wands",
        "arcana": "minor",
    },
    "8": {
        "card_meaning": "Speed, action, air travel, movement, swift change",
        "card_name": "Eight of Wands",
        "card_url": "https://tarot.com/tarot/eight-of-wands/",
        "card_img": "http://i.imgur.com/TaTYcNt.jpg",
        "rank": "eight",
        "suit": "wands",
        "arcana": "minor",
    },
    "9": {
        "card_meaning": "Courage, persistence, test of faith, resilience",
        "card_name": "Nine of Wands",
        "card_url": "https://tarot.com/tarot/nine-of-wands/",
        "card_img": "http://i.imgur.com/qjJdi8J.jpg",
        "rank": "nine",
        "suit": "wands",
        "arcana": "minor",
    },
    "10": {
        "card_meaning": "Burden, responsibility, hard work, stress, achievement",
        "card_name": "Ten of Wands",
        "card_url": "https://tarot.com/tarot/ten-of-wands/",
        "card_img": "http://i.imgur.com/hNC3y5g.jpg",
        "rank": "ten",
        "suit": "wands",
        "arcana": "minor",
    },
    "11": {
        "card_meaning": "Enthusiasm, exploration, discovery, free spirit",
        "card_name": "Page of Wands",
        "card_url": "https://tarot.com/tarot/page-of-wands/",
        "card_img": "http://i.imgur.com/44puitP.jpg",
        "rank": "page",
        "suit": "wands",
        "arcana": "minor",
    },
    "12": {
        "card_meaning": "Energy, passion, lust, action, adventure, impulsiveness",
        "card_name": "Knight of Wands",
        "card_url": "https://tarot.com/tarot/knight-of-wands/",
        "card_img": "http://i.imgur.com/yzCPXQX.jpg",
        "rank": "knight",
        "suit": "wands",
        "arcana": "minor",
    },
    "13": {
        "card_meaning": "Exuberance, warmth, vibrancy, determination",
        "card_name": "Queen of Wands",
        "card_url": "https://tarot.com/tarot/queen-of-wands/",
        "card_img": "http://i.imgur.com/LTeYFqy.jpg",
        "rank": "queen",
        "suit": "wands",
        "arcana": "minor",
    },
    "14": {
        "card_meaning": "Natural-born leader, vision, entrepreneur, honour",
        "card_name": "King of Wands",
        "card_url": "https://tarot.com/tarot/king-of-wands/",
        "card_img": "http://i.imgur.com/iC2Il8N.jpg",
        "rank": "king",
        "suit": "wands",
        "arcana": "minor",
    },
    "15": {
        "card_meaning": "Raw power, victory, break-throughs, mental clarity",
        "card_name": "Ace of Swords",
        "card_url": "https://tarot.com/tarot/ace-of-swords/",
        "card_img": "http://i.imgur.com/ja2tUWE.jpg",
        "rank": "ace",
        "suit": "swords",
        "arcana": "minor",
    },
    "16": {
        "card_meaning": "Indecision, choices, truce, stalemate, blocked emotions",
        "card_name": "Two of Swords",
        "card_url": "https://tarot.com/tarot/two-of-swords/",
        "card_img": "http://i.imgur.com/EBIjsot.jpg",
        "rank": "two",
        "suit": "swords",
        "arcana": "minor",
    },
    "17": {
        "card_meaning": "Painful separation, sorrow heartbreak, grief, rejection",
        "card_name": "Three of Swords",
        "card_url": "https://tarot.com/tarot/three-of-swords/",
        "card_img": "http://i.imgur.com/CkKUNSa.jpg",
        "rank": "three",
        "suit": "swords",
        "arcana": "minor",
    },
    "18": {
        "card_meaning": "Contemplation, recuperation, passivity, relaxation, rest",
        "card_name": "Four of Swords",
        "card_url": "https://tarot.com/tarot/four-of-swords/",
        "card_img": "http://i.imgur.com/y1psOrh.jpg",
        "rank": "four",
        "suit": "swords",
        "arcana": "minor",
    },
    "19": {
        "card_meaning": "Conflict, tension, loss, defeat, win at all costs, betrayal",
        "card_name": "Five of Swords",
        "card_url": "https://tarot.com/tarot/five-of-swords/",
        "card_img": "http://i.imgur.com/T1pDWbo.jpg",
        "rank": "five",
        "suit": "swords",
        "arcana": "minor",
    },
    "20": {
        "card_meaning": "Regretful but necessary transition, rite of passage",
        "card_name": "Six of Swords",
        "card_url": "https://tarot.com/tarot/six-of-swords/",
        "card_img": "http://i.imgur.com/ddXLubY.jpg",
        "rank": "six",
        "suit": "swords",
        "arcana": "minor",
    },
    "21": {
        "card_meaning": "Betrayal, deception, getting away with something, stealth",
        "card_name": "Seven of Swords",
        "card_url": "https://tarot.com/tarot/seven-of-swords/",
        "card_img": "http://i.imgur.com/6DNu8dU.jpg",
        "rank": "seven",
        "suit": "swords",
        "arcana": "minor",
    },
    "22": {
        "card_meaning": "Isolation, self-imposed restriction, imprisonment",
        "card_name": "Eight of Swords",
        "card_url": "https://tarot.com/tarot/eight-of-swords/",
        "card_img": "http://i.imgur.com/ov9j8pg.jpg",
        "rank": "eight",
        "suit": "swords",
        "arcana": "minor",
    },
    "23": {
        "card_meaning": "Depression, nightmares, intense anxiety, despair",
        "card_name": "Nine of Swords",
        "card_url": "https://tarot.com/tarot/nine-of-swords/",
        "card_img": "http://i.imgur.com/iWl54Xx.jpg",
        "rank": "nine",
        "suit": "swords",
        "arcana": "minor",
    },
    "24": {
        "card_meaning": "Back-stabbed, defeat, crisis, betrayal, endings, loss",
        "card_name": "Ten of Swords",
        "card_url": "https://tarot.com/tarot/ten-of-swords/",
        "card_img": "http://i.imgur.com/NhkCBnz.jpg",
        "rank": "ten",
        "suit": "swords",
        "arcana": "minor",
    },
    "25": {
        "card_meaning": "Talkative, curious, mentally restless, energetic",
        "card_name": "Page of Swords",
        "card_url": "https://tarot.com/tarot/page-of-swords/",
        "card_img": "http://i.imgur.com/decjazD.jpg",
        "rank": "page",
        "suit": "swords",
        "arcana": "minor",
    },
    "26": {
        "card_meaning": "Opinionated, hasty, action-oriented, communicative",
        "card_name": "Knight of Swords",
        "card_url": "https://tarot.com/tarot/knight-of-swords/",
        "card_img": "http://i.imgur.com/p87LNk8.jpg",
        "rank": "knight",
        "suit": "swords",
        "arcana": "minor",
    },
    "27": {
        "card_meaning": "Quick thinker, organised, perceptive, independent",
        "card_name": "Queen of Swords",
        "card_url": "https://tarot.com/tarot/queen-of-swords/",
        "card_img": "http://i.imgur.com/vgTOeBk.jpg",
        "rank": "queen",
        "suit": "swords",
        "arcana": "minor",
    },
    "28": {
        "card_meaning": "Clear thinking, intellectual power, authority, truth",
        "card_name": "King of Swords",
        "card_url": "https://tarot.com/tarot/king-of-swords/",
        "card_img": "http://i.imgur.com/Y0EtbYp.jpg",
        "rank": "king",
        "suit": "swords",
        "arcana": "minor",
    },
    "29": {
        "card_meaning": "Love, compassion, creativity, overwhelming emotion",
        "card_name": "Ace of Cups",
        "card_url": "https://tarot.com/tarot/ace-of-cups/",
        "card_img": "http://i.imgur.com/4ZcxuXf.jpg",
        "rank": "ace",
        "suit": "cups",
        "arcana": "minor",
    },
    "30": {
        "card_meaning": "Unified love, partnership, attraction, relationships",
        "card_name": "Two of Cups",
        "card_url": "https://tarot.com/tarot/two-of-cups/",
        "card_img": "http://i.imgur.com/K8MRy5I.jpg",
        "rank": "two",
        "suit": "cups",
        "arcana": "minor",
    },
    "31": {
        "card_meaning": "Celebration, friendship, creativity, community",
        "card_name": "Three of Cups",
        "card_url": "https://tarot.com/tarot/three-of-cups/",
        "card_img": "http://i.imgur.com/lqsvyuD.jpg",
        "rank": "three",
        "suit": "cups",
        "arcana": "minor",
    },
    "32": {
        "card_meaning": "Meditation, contemplation, apathy, re-evaluation",
        "card_name": "Four of Cups",
        "card_url": "https://tarot.com/tarot/four-of-cups/",
        "card_img": "http://i.imgur.com/wd1JMK5.jpg",
        "rank": "four",
        "suit": "cups",
        "arcana": "minor",
    },
    "33": {
        "card_meaning": "Loss, regret, disappointment, despair, bereavement",
        "card_name": "Five of Cups",
        "card_url": "https://tarot.com/tarot/five-of-cups/",
        "card_img": "http://i.imgur.com/8EqDUAa.jpg",
        "rank": "five",
        "suit": "cups",
        "arcana": "minor",
    },
    "34": {
        "card_meaning": "Reunion, nostalgia, childhood memories, innocence",
        "card_name": "Six of Cups",
        "card_url": "https://tarot.com/tarot/six-of-cups/",
        "card_img": "http://i.imgur.com/pA7oFHJ.jpg",
        "rank": "six",
        "suit": "cups",
        "arcana": "minor",
    },
    "35": {
        "card_meaning": "Fantasy, illusion, wishful thinking, choices, imagination",
        "card_name": "Seven of Cups",
        "card_url": "https://tarot.com/tarot/seven-of-cups/",
        "card_img": "http://i.imgur.com/NL300h2.jpg",
        "rank": "seven",
        "suit": "cups",
        "arcana": "minor",
    },
    "36": {
        "card_meaning": "Escapism, disappointment, abandonment, withdrawal",
        "card_name": "Eight of Cups",
        "card_url": "https://tarot.com/tarot/eight-of-cups/",
        "card_img": "http://i.imgur.com/MTgZYuZ.jpg",
        "rank": "eight",
        "suit": "cups",
        "arcana": "minor",
    },
    "37": {
        "card_meaning": "Wishes fulfilled, comfort, happiness, satisfaction",
        "card_name": "Nine of Cups",
        "card_url": "https://tarot.com/tarot/nine-of-cups/",
        "card_img": "http://i.imgur.com/FzW2aGy.jpg",
        "rank": "nine",
        "suit": "cups",
        "arcana": "minor",
    },
    "38": {
        "card_meaning": "Harmony, marriage, happiness, alignment",
        "card_name": "Ten of Cups",
        "card_url": "https://tarot.com/tarot/ten-of-cups/",
        "card_img": "http://i.imgur.com/bEm3wa8.jpg",
        "rank": "ten",
        "suit": "cups",
        "arcana": "minor",
    },
    "39": {
        "card_meaning": "A messenger, creative beginnings, synchronicity",
        "card_name": "Page of Cups",
        "card_url": "https://tarot.com/tarot/page-of-cups/",
        "card_img": "http://i.imgur.com/UvanQ1x.jpg",
        "rank": "page",
        "suit": "cups",
        "arcana": "minor",
    },
    "40": {
        "card_meaning": "Romance, charm, 'Knight in shining armour', imagination",
        "card_name": "Knight of Cups",
        "card_url": "https://tarot.com/tarot/knight-of-cups/",
        "card_img": "http://i.imgur.com/SfpE4cm.jpg",
        "rank": "knight",
        "suit": "cups",
        "arcana": "minor",
    },
    "41": {
        "card_meaning": "Emotional security, calm, intuitive, compassionate",
        "card_name": "Queen of Cups",
        "card_url": "https://tarot.com/tarot/queen-of-cups/",
        "card_img": "http://i.imgur.com/ZVMpaO6.jpg",
        "rank": "queen",
        "suit": "cups",
        "arcana": "minor",
    },
    "42": {
        "card_meaning": "Emotional balance and control, generosity",
        "card_name": "King of Cups",
        "card_url": "https://tarot.com/tarot/king-of-cups/",
        "card_img": "http://i.imgur.com/fW2cZDl.jpg",
        "rank": "king",
        "suit": "cups",
        "arcana": "minor",
    },
    "43": {
        "card_meaning": "Manifestation, new financial opportunity, prosperity",
        "card_name": "Ace of Pentacles",
        "card_url": "https://tarot.com/tarot/ace-of-pentacles/",
        "card_img": "http://i.imgur.com/ebAyNZZ.jpg",
        "rank": "ace",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "44": {
        "card_meaning": "Balance, adaptability, time management, prioritisation",
        "card_name": "Two of Pentacles",
        "card_url": "https://tarot.com/tarot/two-of-pentacles/",
        "card_img": "http://i.imgur.com/F3URp9M.jpg",
        "rank": "two",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "45": {
        "card_meaning": "Teamwork, initial fulfilment, collaboration, learning",
        "card_name": "Three of Pentacles",
        "card_url": "https://tarot.com/tarot/three-of-pentacles/",
        "card_img": "http://i.imgur.com/hzIo13n.jpg",
        "rank": "three",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "46": {
        "card_meaning": "Control, stability, security, possession, conservatism",
        "card_name": "Four of Pentacles",
        "card_url": "https://tarot.com/tarot/four-of-pentacles/",
        "card_img": "http://i.imgur.com/caXXbBL.jpg",
        "rank": "four",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "47": {
        "card_meaning": "Isolation, insecurity, worry, financial loss, poverty",
        "card_name": "Five of Pentacles",
        "card_url": "https://tarot.com/tarot/five-of-pentacles/",
        "card_img": "http://i.imgur.com/hIG43wQ.jpg",
        "rank": "five",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "48": {
        "card_meaning": "Generosity, charity, giving, prosperity, sharing wealth",
        "card_name": "Six of Pentacles",
        "card_url": "https://tarot.com/tarot/six-of-pentacles/",
        "card_img": "http://i.imgur.com/NR2JdPf.jpg",
        "rank": "six",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "49": {
        "card_meaning": "Vision, perseverance, profit, reward, investment",
        "card_name": "Seven of Pentacles",
        "card_url": "https://tarot.com/tarot/seven-of-pentacles/",
        "card_img": "http://i.imgur.com/nYYBX2T.jpg",
        "rank": "seven",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "50": {
        "card_meaning": "Apprenticeship, education, quality, engagement",
        "card_name": "Eight of Pentacles",
        "card_url": "https://tarot.com/tarot/eight-of-pentacles/",
        "card_img": "http://i.imgur.com/rSCcjOv.jpg",
        "rank": "eight",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "51": {
        "card_meaning": "Gratitude, luxury, self-sufficiency, culmination",
        "card_name": "Nine of Pentacles",
        "card_url": "https://tarot.com/tarot/nine-of-pentacles/",
        "card_img": "http://i.imgur.com/TsHqgIQ.jpg",
        "rank": "nine",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "52": {
        "card_meaning": "Wealth, inheritance, family, establishment, retirement",
        "card_name": "Ten of Pentacles",
        "card_url": "https://tarot.com/tarot/ten-of-pentacles/",
        "card_img": "http://i.imgur.com/p8VSgOO.jpg",
        "rank": "ten",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "53": {
        "card_meaning": "Manifestation, financial opportunity, new job",
        "card_name": "Page of Pentacles",
        "card_url": "https://tarot.com/tarot/page-of-pentacles/",
        "card_img": "http://i.imgur.com/WsQEzyQ.jpg",
        "rank": "page",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "54": {
        "card_meaning": "Efficiency, routine, conservatism, methodical",
        "card_name": "Knight of Pentacles",
        "card_url": "https://tarot.com/tarot/knight-of-pentacles/",
        "card_img": "http://i.imgur.com/yEL8ZAr.jpg",
        "rank": "knight",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "55": {
        "card_meaning": "Practical, homely, motherly, down-to-earth, security",
        "card_name": "Queen of Pentacles",
        "card_url": "https://tarot.com/tarot/queen-of-pentacles/",
        "card_img": "http://i.imgur.com/OX60YCi.jpg",
        "rank": "queen",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "56": {
        "card_meaning": "Security, control, power, discipline, abundance",
        "card_name": "King of Pentacles",
        "card_url": "https://tarot.com/tarot/king-of-pentacles/",
        "card_img": "http://i.imgur.com/Dk6tR9R.jpg",
        "rank": "king",
        "suit": "pentacles",
        "arcana": "minor",
    },
    "57": {
        "card_meaning": "Beginnings, innocence, spontaneity, a free spirit",
        "card_name": "Fool",
        "card_url": "https://tarot.com/tarot/the-fool/",
        "card_img": "http://i.imgur.com/vetEoDu.jpg",
        "rank": "fool",
        "suit": "trump",
        "arcana": "major",
    },
    "58": {
        "card_meaning": "Power, skill, concentration, action, resourcefulness",
        "card_name": "Magician",
        "card_url": "https://tarot.com/tarot/the-magician/",
        "card_img": "http://i.imgur.com/9VJLy9S.jpg",
        "rank": "magician",
        "suit": "trump",
        "arcana": "major",
    },
    "59": {
        "card_meaning": "Intuition, Higher powers, mystery, subconscious mind",
        "card_name": "High Priestess",
        "card_url": "https://tarot.com/tarot/the-high-priestess/",
        "card_img": "http://i.imgur.com/bablzG8.jpg",
        "rank": "high_priestess",
        "suit": "trump",
        "arcana": "major",
    },
    "60": {
        "card_meaning": "Fertility, femininity, beauty, nature, abundance",
        "card_name": "Empress",
        "card_url": "https://tarot.com/tarot/the-empress/",
        "card_img": "http://i.imgur.com/sh0Fzdt.jpg",
        "rank": "empress",
        "suit": "trump",
        "arcana": "major",
    },
    "61": {
        "card_meaning": "Authority, father-figure, structure, solid foundation",
        "card_name": "Emperor",
        "card_url": "https://tarot.com/tarot/the-emperor/",
        "card_img": "http://i.imgur.com/sc76hNS.jpg",
        "rank": "emperor",
        "suit": "trump",
        "arcana": "major",
    },
    "62": {
        "card_meaning": "Religion, group identification, conformity, tradition, beliefs",
        "card_name": "Hierophant",
        "card_url": "https://tarot.com/tarot/the-hierophant/",
        "card_img": "http://i.imgur.com/JFvG1um.jpg",
        "rank": "heirophant",
        "suit": "trump",
        "arcana": "major",
    },
    "63": {
        "card_meaning": "Love, union, relationships, values alignment, choices",
        "card_name": "Lovers",
        "card_url": "https://tarot.com/tarot/the-lovers/",
        "card_img": "http://i.imgur.com/U6CcViS.jpg",
        "rank": "lovers",
        "suit": "trump",
        "arcana": "major",
    },
    "64": {
        "card_meaning": "Control, will power, victory, assertion, determination",
        "card_name": "Chariot",
        "card_url": "https://tarot.com/tarot/the-chariot/",
        "card_img": "http://i.imgur.com/xilfsxU.jpg",
        "rank": "chariot",
        "suit": "trump",
        "arcana": "major",
    },
    "65": {
        "card_meaning": "Strength, courage, patience, control, compassion",
        "card_name": "Strength",
        "card_url": "https://tarot.com/tarot/strength/",
        "card_img": "http://i.imgur.com/DhNmgJ5.jpg",
        "rank": "strength",
        "suit": "trump",
        "arcana": "major",
    },
    "66": {
        "card_meaning": "Soul-searching, introspection, being alone, inner guidance",
        "card_name": "Hermit",
        "card_url": "https://tarot.com/tarot/the-hermit/",
        "card_img": "http://i.imgur.com/yTzCitM.jpg",
        "rank": "hermit",
        "suit": "trump",
        "arcana": "major",
    },
    "67": {
        "card_meaning": "Good luck, karma, life cycles, destiny, a turning point",
        "card_name": "Wheel of Fortune",
        "card_url": "https://tarot.com/tarot/wheel-of-fortune/",
        "card_img": "http://i.imgur.com/jrY1gDP.jpg",
        "rank": "wheel_of_fortune",
        "suit": "trump",
        "arcana": "major",
    },
    "68": {
        "card_meaning": "Justice, fairness, truth, cause and effect, law",
        "card_name": "Justice",
        "card_url": "https://tarot.com/tarot/justice/",
        "card_img": "http://i.imgur.com/eyHEpUR.jpg",
        "rank": "justice",
        "suit": "trump",
        "arcana": "major",
    },
    "69": {
        "card_meaning": "Suspension, restriction, letting go, sacrifice",
        "card_name": "Hanged Man",
        "card_url": "https://tarot.com/tarot/the-hanged-man/",
        "card_img": "http://i.imgur.com/b5Sml3N.jpg",
        "rank": "hanged_man",
        "suit": "trump",
        "arcana": "major",
    },
    "70": {
        "card_meaning": "Endings, beginnings, change, transformation, transition",
        "card_name": "Death",
        "card_url": "https://tarot.com/tarot/death/",
        "card_img": "http://i.imgur.com/ujauT3a.jpg",
        "rank": "death",
        "suit": "trump",
        "arcana": "major",
    },
    "71": {
        "card_meaning": "Balance, moderation, patience, purpose, meaning",
        "card_name": "Temperance",
        "card_url": "https://tarot.com/tarot/temperance/",
        "card_img": "http://i.imgur.com/i2iwvA0.jpg",
        "rank": "temperance",
        "suit": "trump",
        "arcana": "major",
    },
    "72": {
        "card_meaning": "Bondage, addiction, sexuality, materialism",
        "card_name": "Devil",
        "card_url": "https://tarot.com/tarot/the-devil/",
        "card_img": "http://i.imgur.com/ChhcGKF.jpg",
        "rank": "devil",
        "suit": "trump",
        "arcana": "major",
    },
    "73": {
        "card_meaning": "Disaster, upheaval, sudden change, revelation",
        "card_name": "Tower",
        "card_url": "https://tarot.com/tarot/the-tower/",
        "card_img": "http://i.imgur.com/ZYpEMKl.jpg",
        "rank": "tower",
        "suit": "trump",
        "arcana": "major",
    },
    "74": {
        "card_meaning": "Hope, spirituality, renewal, inspiration, serenity",
        "card_name": "Star",
        "card_url": "https://tarot.com/tarot/the-star/",
        "card_img": "http://i.imgur.com/2X56bTd.jpg",
        "rank": "star",
        "suit": "trump",
        "arcana": "major",
    },
    "75": {
        "card_meaning": "Illusion, fear, anxiety, insecurity, subconscious",
        "card_name": "Moon",
        "card_url": "https://tarot.com/tarot/the-moon/",
        "card_img": "http://i.imgur.com/8Cpfekc.jpg",
        "rank": "moon",
        "suit": "trump",
        "arcana": "major",
    },
    "76": {
        "card_meaning": "Fun, warmth, success, positivity, vitality",
        "card_name": "Sun",
        "card_url": "https://tarot.com/tarot/the-sun/",
        "card_img": "http://i.imgur.com/zgJJy7b.jpg",
        "rank": "sun",
        "suit": "trump",
        "arcana": "major",
    },
    "77": {
        "card_meaning": "Judgement, rebirth, inner calling, absolution",
        "card_name": "Judgement",
        "card_url": "https://tarot.com/tarot/judgement/",
        "card_img": "http://i.imgur.com/JyALFQF.jpg",
        "rank": "judgement",
        "suit": "trump",
        "arcana": "major",
    },
    "78": {
        "card_meaning": "Completion, integration, accomplishment, travel",
        "card_name": "World",
        "card_url": "https://tarot.com/tarot/the-world/",
        "card_img": "http://i.imgur.com/3ZncYkn.jpg",
        "rank": "world",
        "suit": "trump",
        "arcana": "major",
    },
}
