blank_template = [
    {
        "badge_name": "cia",
        "code": "CIA",
        "file_name": "https://i.imgur.com/QkDQoqh.png",
        "is_inverted": False,
    },
    {
        "badge_name": "discord",
        "code": "DISCORD",
        "file_name": "https://i.imgur.com/Q4zkz9k.png",
        "is_inverted": False,
    },
    {
        "badge_name": "cicada",
        "code": "CICADA",
        "file_name": "https://i.imgur.com/DktANMF.png",
        "is_inverted": False,
    },
    {
        "badge_name": "ioi",
        "code": "IOI",
        "file_name": "https://i.imgur.com/kYiSeFf.png",
        "is_inverted": False,
    },
    {
        "badge_name": "fbi",
        "code": "FBI",
        "file_name": "https://i.imgur.com/5yM0hy8.png",
        "is_inverted": False,
    },
    {
        "badge_name": "nsa",
        "code": "NSA",
        "file_name": "https://i.imgur.com/zW3nCgx.png",
        "is_inverted": False,
    },
    {
        "badge_name": "gab",
        "code": "GAB",
        "file_name": "https://i.imgur.com/zS50DI0.png",
        "is_inverted": False,
    },
    {
        "badge_name": "dop",
        "code": "DOP",
        "file_name": "https://i.imgur.com/GbX8MxD.png",
        "is_inverted": False,
    },
    {
        "badge_name": "shit",
        "code": "SHIT",
        "file_name": "https://i.imgur.com/HK6ieKq.png",
        "is_inverted": False,
    },
    {
        "badge_name": "bunker",
        "code": "BUNKER",
        "file_name": "https://i.imgur.com/BTVHKMb.png",
        "is_inverted": False,
    },
    {
        "badge_name": "dprk",
        "code": "DPRK",
        "file_name": "https://i.imgur.com/PkmicXZ.png",
        "is_inverted": False,
    },
    {
        "badge_name": "kek",
        "code": "KEK",
        "file_name": "https://i.imgur.com/SMyXZBg.png",
        "is_inverted": False,
    },
    {
        "badge_name": "dhs",
        "code": "SpaceX",
        "file_name": "https://i.imgur.com/ibtbEjr.png",
        "is_inverted": False,
    },
    {
        "badge_name": "unsc",
        "code": "UNSC",
        "file_name": "https://i.imgur.com/OnnWRfL.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Anahein Ducks",
        "code": "ANA",
        "file_name": "https://i.imgur.com/cOELhhT.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Arizona Coyotes",
        "code": "ARI",
        "file_name": "https://i.imgur.com/IjXyvtM.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Boston Bruins",
        "code": "BOS",
        "file_name": "https://i.imgur.com/muRcEUm.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Buffalo Sabres",
        "code": "BUF",
        "file_name": "https://i.imgur.com/8RBNDzH.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Calgary Flames",
        "code": "CGY",
        "file_name": "https://i.imgur.com/Ps0m7ww.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Carolina Hurricanes",
        "code": "CAR",
        "file_name": "https://i.imgur.com/gWX73Fo.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Chicago Blackhawks",
        "code": "CHI",
        "file_name": "https://i.imgur.com/XBHEtej.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Colorado Avalanche",
        "code": "COL",
        "file_name": "https://i.imgur.com/oaZfakk.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Columbus Blue Jackets",
        "code": "CBJ",
        "file_name": "https://i.imgur.com/DStIvvx.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Dallas Stars",
        "code": "DAL",
        "file_name": "https://i.imgur.com/3ZxaXNG.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Detroit Red Wings",
        "code": "DET",
        "file_name": "https://i.imgur.com/c1wNMDg.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Edmonton Oilers",
        "code": "EDM",
        "file_name": "https://i.imgur.com/gAnvRNH.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Florida Panthers",
        "code": "FLA",
        "file_name": "https://i.imgur.com/D7XIS4S.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Los Angeles Kings",
        "code": "LAK",
        "file_name": "https://i.imgur.com/ljQJpO8.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Minnesota Wild",
        "code": "MIN",
        "file_name": "https://i.imgur.com/5sJiDKO.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Montréal Canadiens",
        "code": "MTL",
        "file_name": "https://i.imgur.com/Izikpfh.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Nashville Predators",
        "code": "NSH",
        "file_name": "https://i.imgur.com/acFYYjG.png",
        "is_inverted": False,
    },
    {
        "badge_name": "New Jersey Devils",
        "code": "NJD",
        "file_name": "https://i.imgur.com/3iTGZ5g.png",
        "is_inverted": False,
    },
    {
        "badge_name": "New York Islanders",
        "code": "NYI",
        "file_name": "https://i.imgur.com/hiFB2ol.png",
        "is_inverted": False,
    },
    {
        "badge_name": "New York Rangers",
        "code": "NYR",
        "file_name": "https://i.imgur.com/sUGtyVT.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Ottawa Senators",
        "code": "OTT",
        "file_name": "https://i.imgur.com/eNCJ2Kw.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Philadelphia Flyers",
        "code": "PHI",
        "file_name": "https://i.imgur.com/X8rh7sw.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Pittsburgh Penguins",
        "code": "PIT",
        "file_name": "https://i.imgur.com/YXepjgK.png",
        "is_inverted": False,
    },
    {
        "badge_name": "San Jose Sharks",
        "code": "SJS",
        "file_name": "https://i.imgur.com/KPlna0Y.png",
        "is_inverted": False,
    },
    {
        "badge_name": "St. Louis Blues",
        "code": "STL",
        "file_name": "https://i.imgur.com/Qb7kpwc.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Tampa Bay Lightning",
        "code": "TBL",
        "file_name": "https://i.imgur.com/BwiKWwv.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Toronto Maple Leafs",
        "code": "TOR",
        "file_name": "https://i.imgur.com/MuiYOFx.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Vancouver Canucks",
        "code": "VAN",
        "file_name": "https://i.imgur.com/qGEH80F.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Vegas Golden Knights",
        "code": "VGK",
        "file_name": "https://i.imgur.com/SqUjpK7.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Washington Capitals",
        "code": "WSH",
        "file_name": "https://i.imgur.com/lToLSgL.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Winnipeg Jets",
        "code": "WPG",
        "file_name": "https://i.imgur.com/e6zr2O7.png",
        "is_inverted": False,
    },
]
