FLAGS = {
    "🇦🇩": {"code": "ca", "country": "Andorra", "name": "Catalan"},
    "🇦🇪": {"code": "ar", "country": "United Arab Emirates", "name": "Arabic"},
    "🇦🇫": {"code": "ps", "country": "Afghanistan", "name": "Pashto"},
    "🇦🇬": {"code": "en", "country": "Antigua and Barbuda", "name": "English"},
    "🇦🇮": {"code": "en", "country": "Anguilla", "name": "English"},
    "🇦🇱": {"code": "sq", "country": "Albania", "name": "Albanian"},
    "🇦🇲": {"code": "hy", "country": "Armenia", "name": "Armenian"},
    "🇦🇴": {"code": "pt", "country": "Angola", "name": "Portuguese"},
    "🇦🇶": {"code": "en", "country": "Antarctica", "name": "English"},
    "🇦🇷": {"code": "es", "country": "Argentina", "name": "Spanish"},
    "🇦🇸": {"code": "en", "country": "American Samoa", "name": "English"},
    "🇦🇹": {"code": "de", "country": "Austria", "name": "German"},
    "🇦🇺": {"code": "en", "country": "Australia", "name": "English"},
    "🇦🇼": {"code": "nl", "country": "Aruba", "name": "Dutch"},
    "🇦🇽": {"code": "sv", "country": "Åland Islands", "name": "Swedish"},
    "🇦🇿": {"code": "az", "country": "Azerbaijan", "name": "Azerbaijani"},
    "🇧🇦": {"code": "bs", "country": "Bosnia and Herzegovina", "name": "Bosnian"},
    "🇧🇧": {"code": "en", "country": "Barbados", "name": "English"},
    "🇧🇩": {"code": "bn", "country": "Bangladesh", "name": "Bengali"},
    "🇧🇪": {"code": "nl", "country": "Belgium", "name": "Dutch"},
    "🇧🇫": {"code": "fr", "country": "Burkina Faso", "name": "French"},
    "🇧🇬": {"code": "bg", "country": "Bulgaria", "name": "Bulgarian"},
    "🇧🇭": {"code": "ar", "country": "Bahrain", "name": "Arabic"},
    "🇧🇮": {"code": "fr", "country": "Burundi", "name": "French"},
    "🇧🇯": {"code": "fr", "country": "Benin", "name": "French"},
    "🇧🇱": {"code": "fr", "country": "Saint Barthélemy", "name": "French"},
    "🇧🇲": {"code": "en", "country": "Bermuda", "name": "English"},
    "🇧🇳": {"code": "ms", "country": "Brunei Darussalam", "name": "Malay"},
    "🇧🇴": {"code": "es", "country": "Bolivia (Plurinational State of)", "name": "Spanish"},
    "🇧🇶": {"code": "nl", "country": "Bonaire, Sint Eustatius and Saba", "name": "Dutch"},
    "🇧🇷": {"code": "pt", "country": "Brazil", "name": "Portuguese"},
    "🇧🇸": {"code": "en", "country": "Bahamas", "name": "English"},
    "🇧🇹": {"code": "dz", "country": "Bhutan", "name": "Dzongkha"},
    "🇧🇻": {"code": "no", "country": "Bouvet Island", "name": "Norwegian"},
    "🇧🇼": {"code": "en", "country": "Botswana", "name": "English"},
    "🇧🇾": {"code": "be", "country": "Belarus", "name": "Belarusian"},
    "🇧🇿": {"code": "en", "country": "Belize", "name": "English"},
    "🇨🇦": {"code": "en", "country": "Canada", "name": "English"},
    "🇨🇨": {"code": "en", "country": "Cocos (Keeling) Islands", "name": "English"},
    "🇨🇩": {"code": "fr", "country": "Congo (Democratic Republic of the)", "name": "French"},
    "🇨🇫": {"code": "fr", "country": "Central African Republic", "name": "French"},
    "🇨🇬": {"code": "fr", "country": "Congo", "name": "French"},
    "🇨🇭": {"code": "de", "country": "Switzerland", "name": "German"},
    "🇨🇮": {"code": "fr", "country": "Côte d'Ivoire", "name": "French"},
    "🇨🇰": {"code": "en", "country": "Cook Islands", "name": "English"},
    "🇨🇱": {"code": "es", "country": "Chile", "name": "Spanish"},
    "🇨🇲": {"code": "en", "country": "Cameroon", "name": "English"},
    "🇨🇳": {"code": "zh", "country": "China", "name": "Chinese"},
    "🇨🇴": {"code": "es", "country": "Colombia", "name": "Spanish"},
    "🇨🇷": {"code": "es", "country": "Costa Rica", "name": "Spanish"},
    "🇨🇺": {"code": "es", "country": "Cuba", "name": "Spanish"},
    "🇨🇻": {"code": "pt", "country": "Cabo Verde", "name": "Portuguese"},
    "🇨🇼": {"code": "nl", "country": "Curaçao", "name": "Dutch"},
    "🇨🇽": {"code": "en", "country": "Christmas Island", "name": "English"},
    "🇨🇾": {"code": "el", "country": "Cyprus", "name": "Greek (modern)"},
    "🇨🇿": {"code": "cs", "country": "Czech Republic", "name": "Czech"},
    "🇩🇪": {"code": "de", "country": "Germany", "name": "German"},
    "🇩🇯": {"code": "fr", "country": "Djibouti", "name": "French"},
    "🇩🇰": {"code": "da", "country": "Denmark", "name": "Danish"},
    "🇩🇲": {"code": "en", "country": "Dominica", "name": "English"},
    "🇩🇴": {"code": "es", "country": "Dominican Republic", "name": "Spanish"},
    "🇩🇿": {"code": "ar", "country": "Algeria", "name": "Arabic"},
    "🇪🇨": {"code": "es", "country": "Ecuador", "name": "Spanish"},
    "🇪🇪": {"code": "et", "country": "Estonia", "name": "Estonian"},
    "🇪🇬": {"code": "ar", "country": "Egypt", "name": "Arabic"},
    "🇪🇭": {"code": "es", "country": "Western Sahara", "name": "Spanish"},
    "🇪🇷": {"code": "ti", "country": "Eritrea", "name": "Tigrinya"},
    "🇪🇸": {"code": "es", "country": "Spain", "name": "Spanish"},
    "🇪🇹": {"code": "am", "country": "Ethiopia", "name": "Amharic"},
    "🇪🇺": {
        "code": "EU",
        "emoji": "🇪🇺",
        "message": "Not Found",
        "name": "European Union",
        "status": 404,
        "title": "flag for European Union",
        "unicode": "U+1F1EA U+1F1FA",
        "country": "N/A",
    },
    "🇫🇮": {"code": "fi", "country": "Finland", "name": "Finnish"},
    "🇫🇯": {"code": "en", "country": "Fiji", "name": "English"},
    "🇫🇰": {"code": "en", "country": "Falkland Islands (Malvinas)", "name": "English"},
    "🇫🇲": {"code": "en", "country": "Micronesia (Federated States of)", "name": "English"},
    "🇫🇴": {"code": "fo", "country": "Faroe Islands", "name": "Faroese"},
    "🇫🇷": {"code": "fr", "country": "France", "name": "French"},
    "🇬🇦": {"code": "fr", "country": "Gabon", "name": "French"},
    "🇬🇧": {
        "code": "en",
        "country": "United Kingdom of Great Britain and Northern Ireland",
        "name": "English",
    },
    "🇬🇩": {"code": "en", "country": "Grenada", "name": "English"},
    "🇬🇪": {"code": "ka", "country": "Georgia", "name": "Georgian"},
    "🇬🇫": {"code": "fr", "country": "French Guiana", "name": "French"},
    "🇬🇬": {"code": "en", "country": "Guernsey", "name": "English"},
    "🇬🇭": {"code": "en", "country": "Ghana", "name": "English"},
    "🇬🇮": {"code": "en", "country": "Gibraltar", "name": "English"},
    "🇬🇱": {"code": "kl", "country": "Greenland", "name": "Kalaallisut"},
    "🇬🇲": {"code": "en", "country": "Gambia", "name": "English"},
    "🇬🇳": {"code": "fr", "country": "Guinea", "name": "French"},
    "🇬🇵": {"code": "fr", "country": "Guadeloupe", "name": "French"},
    "🇬🇶": {"code": "es", "country": "Equatorial Guinea", "name": "Spanish"},
    "🇬🇷": {"code": "el", "country": "Greece", "name": "Greek (modern)"},
    "🇬🇸": {
        "code": "en",
        "country": "South Georgia and the South Sandwich Islands",
        "name": "English",
    },
    "🇬🇹": {"code": "es", "country": "Guatemala", "name": "Spanish"},
    "🇬🇺": {"code": "en", "country": "Guam", "name": "English"},
    "🇬🇼": {"code": "pt", "country": "Guinea-Bissau", "name": "Portuguese"},
    "🇬🇾": {"code": "en", "country": "Guyana", "name": "English"},
    "🇭🇰": {"code": "en", "country": "Hong Kong", "name": "English"},
    "🇭🇲": {"code": "en", "country": "Heard Island and McDonald Islands", "name": "English"},
    "🇭🇳": {"code": "es", "country": "Honduras", "name": "Spanish"},
    "🇭🇷": {"code": "hr", "country": "Croatia", "name": "Croatian"},
    "🇭🇹": {"code": "fr", "country": "Haiti", "name": "French"},
    "🇭🇺": {"code": "hu", "country": "Hungary", "name": "Hungarian"},
    "🇮🇩": {"code": "id", "country": "Indonesia", "name": "Indonesian"},
    "🇮🇪": {"code": "ga", "country": "Ireland", "name": "Irish"},
    "🇮🇱": {"code": "he", "country": "Israel", "name": "Hebrew (modern)"},
    "🇮🇲": {"code": "en", "country": "Isle of Man", "name": "English"},
    "🇮🇳": {"code": "hi", "country": "India", "name": "Hindi"},
    "🇮🇴": {"code": "en", "country": "British Indian Ocean Territory", "name": "English"},
    "🇮🇶": {"code": "ar", "country": "Iraq", "name": "Arabic"},
    "🇮🇷": {"code": "fa", "country": "Iran (Islamic Republic of)", "name": "Persian (Farsi)"},
    "🇮🇸": {"code": "is", "country": "Iceland", "name": "Icelandic"},
    "🇮🇹": {"code": "it", "country": "Italy", "name": "Italian"},
    "🇯🇪": {"code": "en", "country": "Jersey", "name": "English"},
    "🇯🇲": {"code": "en", "country": "Jamaica", "name": "English"},
    "🇯🇴": {"code": "ar", "country": "Jordan", "name": "Arabic"},
    "🇯🇵": {"code": "ja", "country": "Japan", "name": "Japanese"},
    "🇰🇪": {"code": "en", "country": "Kenya", "name": "English"},
    "🇰🇬": {"code": "ky", "country": "Kyrgyzstan", "name": "Kyrgyz"},
    "🇰🇭": {"code": "km", "country": "Cambodia", "name": "Khmer"},
    "🇰🇮": {"code": "en", "country": "Kiribati", "name": "English"},
    "🇰🇲": {"code": "ar", "country": "Comoros", "name": "Arabic"},
    "🇰🇳": {"code": "en", "country": "Saint Kitts and Nevis", "name": "English"},
    "🇰🇵": {"code": "ko", "country": "Korea (Democratic People's Republic of)", "name": "Korean"},
    "🇰🇷": {"code": "ko", "country": "Korea (Republic of)", "name": "Korean"},
    "🇰🇼": {"code": "ar", "country": "Kuwait", "name": "Arabic"},
    "🇰🇾": {"code": "en", "country": "Cayman Islands", "name": "English"},
    "🇰🇿": {"code": "kk", "country": "Kazakhstan", "name": "Kazakh"},
    "🇱🇦": {"code": "lo", "country": "Lao People's Democratic Republic", "name": "Lao"},
    "🇱🇧": {"code": "ar", "country": "Lebanon", "name": "Arabic"},
    "🇱🇨": {"code": "en", "country": "Saint Lucia", "name": "English"},
    "🇱🇮": {"code": "de", "country": "Liechtenstein", "name": "German"},
    "🇱🇰": {"code": "si", "country": "Sri Lanka", "name": "Sinhalese"},
    "🇱🇷": {"code": "en", "country": "Liberia", "name": "English"},
    "🇱🇸": {"code": "en", "country": "Lesotho", "name": "English"},
    "🇱🇹": {"code": "lt", "country": "Lithuania", "name": "Lithuanian"},
    "🇱🇺": {"code": "fr", "country": "Luxembourg", "name": "French"},
    "🇱🇻": {"code": "lv", "country": "Latvia", "name": "Latvian"},
    "🇱🇾": {"code": "ar", "country": "Libya", "name": "Arabic"},
    "🇲🇦": {"code": "ar", "country": "Morocco", "name": "Arabic"},
    "🇲🇨": {"code": "fr", "country": "Monaco", "name": "French"},
    "🇲🇩": {"code": "ro", "country": "Moldova (Republic of)", "name": "Romanian"},
    "🇲🇪": {"code": "sr", "country": "Montenegro", "name": "Serbian"},
    "🇲🇫": {"code": "en", "country": "Saint Martin (French part)", "name": "English"},
    "🇲🇬": {"code": "fr", "country": "Madagascar", "name": "French"},
    "🇲🇭": {"code": "en", "country": "Marshall Islands", "name": "English"},
    "🇲🇰": {
        "code": "mk",
        "country": "Macedonia (the former Yugoslav Republic of)",
        "name": "Macedonian",
    },
    "🇲🇱": {"code": "fr", "country": "Mali", "name": "French"},
    "🇲🇲": {"code": "my", "country": "Myanmar", "name": "Burmese"},
    "🇲🇳": {"code": "mn", "country": "Mongolia", "name": "Mongolian"},
    "🇲🇴": {"code": "zh", "country": "Macao", "name": "Chinese"},
    "🇲🇵": {"code": "en", "country": "Northern Mariana Islands", "name": "English"},
    "🇲🇶": {"code": "fr", "country": "Martinique", "name": "French"},
    "🇲🇷": {"code": "ar", "country": "Mauritania", "name": "Arabic"},
    "🇲🇸": {"code": "en", "country": "Montserrat", "name": "English"},
    "🇲🇹": {"code": "mt", "country": "Malta", "name": "Maltese"},
    "🇲🇺": {"code": "en", "country": "Mauritius", "name": "English"},
    "🇲🇻": {"code": "dv", "country": "Maldives", "name": "Divehi"},
    "🇲🇼": {"code": "en", "country": "Malawi", "name": "English"},
    "🇲🇽": {"code": "es", "country": "Mexico", "name": "Spanish"},
    "🇲🇾": {"code": "", "country": "Malaysia", "name": "Malaysian"},
    "🇲🇿": {"code": "pt", "country": "Mozambique", "name": "Portuguese"},
    "🇳🇦": {"code": "en", "country": "Namibia", "name": "English"},
    "🇳🇨": {"code": "fr", "country": "New Caledonia", "name": "French"},
    "🇳🇪": {"code": "fr", "country": "Niger", "name": "French"},
    "🇳🇫": {"code": "en", "country": "Norfolk Island", "name": "English"},
    "🇳🇬": {"code": "en", "country": "Nigeria", "name": "English"},
    "🇳🇮": {"code": "es", "country": "Nicaragua", "name": "Spanish"},
    "🇳🇱": {"code": "nl", "country": "Netherlands", "name": "Dutch"},
    "🇳🇴": {"code": "no", "country": "Norway", "name": "Norwegian"},
    "🇳🇵": {"code": "ne", "country": "Nepal", "name": "Nepali"},
    "🇳🇷": {"code": "en", "country": "Nauru", "name": "English"},
    "🇳🇺": {"code": "en", "country": "Niue", "name": "English"},
    "🇳🇿": {"code": "en", "country": "New Zealand", "name": "English"},
    "🇴🇲": {"code": "ar", "country": "Oman", "name": "Arabic"},
    "🇵🇦": {"code": "es", "country": "Panama", "name": "Spanish"},
    "🇵🇪": {"code": "es", "country": "Peru", "name": "Spanish"},
    "🇵🇫": {"code": "fr", "country": "French Polynesia", "name": "French"},
    "🇵🇬": {"code": "en", "country": "Papua New Guinea", "name": "English"},
    "🇵🇭": {"code": "tl", "country": "Philippines", "name": "Tagalog (Filipino)"},
    "🇵🇰": {"code": "en", "country": "Pakistan", "name": "English"},
    "🇵🇱": {"code": "pl", "country": "Poland", "name": "Polish"},
    "🇵🇲": {"code": "fr", "country": "Saint Pierre and Miquelon", "name": "French"},
    "🇵🇳": {"code": "en", "country": "Pitcairn", "name": "English"},
    "🇵🇷": {"code": "es", "country": "Puerto Rico", "name": "Spanish"},
    "🇵🇸": {"code": "ar", "country": "Palestine, State of", "name": "Arabic"},
    "🇵🇹": {"code": "pt", "country": "Portugal", "name": "Portuguese"},
    "🇵🇼": {"code": "en", "country": "Palau", "name": "English"},
    "🇵🇾": {"code": "es", "country": "Paraguay", "name": "Spanish"},
    "🇶🇦": {"code": "ar", "country": "Qatar", "name": "Arabic"},
    "🇷🇪": {"code": "fr", "country": "Réunion", "name": "French"},
    "🇷🇴": {"code": "ro", "country": "Romania", "name": "Romanian"},
    "🇷🇸": {"code": "sr", "country": "Serbia", "name": "Serbian"},
    "🇷🇺": {"code": "ru", "country": "Russian Federation", "name": "Russian"},
    "🇷🇼": {"code": "rw", "country": "Rwanda", "name": "Kinyarwanda"},
    "🇸🇦": {"code": "ar", "country": "Saudi Arabia", "name": "Arabic"},
    "🇸🇧": {"code": "en", "country": "Solomon Islands", "name": "English"},
    "🇸🇨": {"code": "fr", "country": "Seychelles", "name": "French"},
    "🇸🇩": {"code": "ar", "country": "Sudan", "name": "Arabic"},
    "🇸🇪": {"code": "sv", "country": "Sweden", "name": "Swedish"},
    "🇸🇬": {"code": "en", "country": "Singapore", "name": "English"},
    "🇸🇭": {
        "code": "en",
        "country": "Saint Helena, Ascension and Tristan da Cunha",
        "name": "English",
    },
    "🇸🇮": {"code": "sl", "country": "Slovenia", "name": "Slovene"},
    "🇸🇯": {"code": "no", "country": "Svalbard and Jan Mayen", "name": "Norwegian"},
    "🇸🇰": {"code": "sk", "country": "Slovakia", "name": "Slovak"},
    "🇸🇱": {"code": "en", "country": "Sierra Leone", "name": "English"},
    "🇸🇲": {"code": "it", "country": "San Marino", "name": "Italian"},
    "🇸🇳": {"code": "fr", "country": "Senegal", "name": "French"},
    "🇸🇴": {"code": "so", "country": "Somalia", "name": "Somali"},
    "🇸🇷": {"code": "nl", "country": "Suriname", "name": "Dutch"},
    "🇸🇸": {"code": "en", "country": "South Sudan", "name": "English"},
    "🇸🇹": {"code": "pt", "country": "Sao Tome and Principe", "name": "Portuguese"},
    "🇸🇻": {"code": "es", "country": "El Salvador", "name": "Spanish"},
    "🇸🇽": {"code": "nl", "country": "Sint Maarten (Dutch part)", "name": "Dutch"},
    "🇸🇾": {"code": "ar", "country": "Syrian Arab Republic", "name": "Arabic"},
    "🇸🇿": {"code": "en", "country": "Swaziland", "name": "English"},
    "🇹🇨": {"code": "en", "country": "Turks and Caicos Islands", "name": "English"},
    "🇹🇩": {"code": "fr", "country": "Chad", "name": "French"},
    "🇹🇫": {"code": "fr", "country": "French Southern Territories", "name": "French"},
    "🇹🇬": {"code": "fr", "country": "Togo", "name": "French"},
    "🇹🇭": {"code": "th", "country": "Thailand", "name": "Thai"},
    "🇹🇯": {"code": "tg", "country": "Tajikistan", "name": "Tajik"},
    "🇹🇰": {"code": "en", "country": "Tokelau", "name": "English"},
    "🇹🇱": {"code": "pt", "country": "Timor-Leste", "name": "Portuguese"},
    "🇹🇲": {"code": "tk", "country": "Turkmenistan", "name": "Turkmen"},
    "🇹🇳": {"code": "ar", "country": "Tunisia", "name": "Arabic"},
    "🇹🇴": {"code": "en", "country": "Tonga", "name": "English"},
    "🇹🇷": {"code": "tr", "country": "Turkey", "name": "Turkish"},
    "🇹🇹": {"code": "en", "country": "Trinidad and Tobago", "name": "English"},
    "🇹🇻": {"code": "en", "country": "Tuvalu", "name": "English"},
    "🇹🇼": {"code": "zh", "country": "Taiwan", "name": "Chinese"},
    "🇹🇿": {"code": "sw", "country": "Tanzania, United Republic of", "name": "Swahili"},
    "🇺🇦": {"code": "uk", "country": "Ukraine", "name": "Ukrainian"},
    "🇺🇬": {"code": "en", "country": "Uganda", "name": "English"},
    "🇺🇲": {"code": "en", "country": "United States Minor Outlying Islands", "name": "English"},
    "🇺🇸": {"code": "en", "country": "United States of America", "name": "English"},
    "🇺🇾": {"code": "es", "country": "Uruguay", "name": "Spanish"},
    "🇺🇿": {"code": "uz", "country": "Uzbekistan", "name": "Uzbek"},
    "🇻🇦": {"code": "la", "country": "Holy See", "name": "Latin"},
    "🇻🇨": {"code": "en", "country": "Saint Vincent and the Grenadines", "name": "English"},
    "🇻🇪": {"code": "es", "country": "Venezuela (Bolivarian Republic of)", "name": "Spanish"},
    "🇻🇬": {"code": "en", "country": "Virgin Islands (British)", "name": "English"},
    "🇻🇮": {"code": "en", "country": "Virgin Islands (U.S.)", "name": "English"},
    "🇻🇳": {"code": "vi", "country": "Viet Nam", "name": "Vietnamese"},
    "🇻🇺": {"code": "bi", "country": "Vanuatu", "name": "Bislama"},
    "🇼🇫": {"code": "fr", "country": "Wallis and Futuna", "name": "French"},
    "🇼🇸": {"code": "sm", "country": "Samoa", "name": "Samoan"},
    "🇾🇪": {"code": "ar", "country": "Yemen", "name": "Arabic"},
    "🇾🇹": {"code": "fr", "country": "Mayotte", "name": "French"},
    "🇿🇦": {"code": "af", "country": "South Africa", "name": "Afrikaans"},
    "🇿🇲": {"code": "en", "country": "Zambia", "name": "English"},
    "🇿🇼": {"code": "en", "country": "Zimbabwe", "name": "English"},
}
