import re

regionals = {
    "a": "\N{REGIONAL INDICATOR SYMBOL LETTER A}",
    "b": "\N{REGIONAL INDICATOR SYMBOL LETTER B}",
    "c": "\N{REGIONAL INDICATOR SYMBOL LETTER C}",
    "d": "\N{REGIONAL INDICATOR SYMBOL LETTER D}",
    "e": "\N{REGIONAL INDICATOR SYMBOL LETTER E}",
    "f": "\N{REGIONAL INDICATOR SYMBOL LETTER F}",
    "g": "\N{REGIONAL INDICATOR SYMBOL LETTER G}",
    "h": "\N{REGIONAL INDICATOR SYMBOL LETTER H}",
    "i": "\N{REGIONAL INDICATOR SYMBOL LETTER I}",
    "j": "\N{REGIONAL INDICATOR SYMBOL LETTER J}",
    "k": "\N{REGIONAL INDICATOR SYMBOL LETTER K}",
    "l": "\N{REGIONAL INDICATOR SYMBOL LETTER L}",
    "m": "\N{REGIONAL INDICATOR SYMBOL LETTER M}",
    "n": "\N{REGIONAL INDICATOR SYMBOL LETTER N}",
    "o": "\N{REGIONAL INDICATOR SYMBOL LETTER O}",
    "p": "\N{REGIONAL INDICATOR SYMBOL LETTER P}",
    "q": "\N{REGIONAL INDICATOR SYMBOL LETTER Q}",
    "r": "\N{REGIONAL INDICATOR SYMBOL LETTER R}",
    "s": "\N{REGIONAL INDICATOR SYMBOL LETTER S}",
    "t": "\N{REGIONAL INDICATOR SYMBOL LETTER T}",
    "u": "\N{REGIONAL INDICATOR SYMBOL LETTER U}",
    "v": "\N{REGIONAL INDICATOR SYMBOL LETTER V}",
    "w": "\N{REGIONAL INDICATOR SYMBOL LETTER W}",
    "x": "\N{REGIONAL INDICATOR SYMBOL LETTER X}",
    "y": "\N{REGIONAL INDICATOR SYMBOL LETTER Y}",
    "z": "\N{REGIONAL INDICATOR SYMBOL LETTER Z}",
    "0": "0⃣",
    "1": "1⃣",
    "2": "2⃣",
    "3": "3⃣",
    "4": "4⃣",
    "5": "5⃣",
    "6": "6⃣",
    "7": "7⃣",
    "8": "8⃣",
    "9": "9⃣",
    "!": "\u2757",
    "?": "\u2753",
}
emoji_reg = re.compile(r"<:.+?:([0-9]{15,21})>")
ball = [
    "It is certain",
    "It is decidedly so",
    "Without a doubt",
    "Yes definitely",
    "You may rely on it",
    "As I see it, yes",
    "Most likely",
    "Outlook good",
    "Yes",
    "Signs point to yes",
    "Reply hazy try again",
    "Ask again later",
    "Better not tell you now",
    "Cannot predict now",
    "Concentrate and ask again",
    "Don't count on it",
    "My reply is no",
    "My sources say no",
    "Outlook not so good",
    "Very doubtful",
]
emoji_dict = {
    # these arrays are in order of "most desirable". Put emojis that most convincingly correspond to their letter near the front of each array.
    "a": ["🇦", "🅰", "🍙", "🔼", "4⃣"],
    "b": ["🇧", "🅱", "8⃣"],
    "c": ["🇨", "©", "🗜"],
    "d": ["🇩", "↩"],
    "e": ["🇪", "3⃣", "📧", "💶"],
    "f": ["🇫", "🎏"],
    "g": ["🇬", "🗜", "6⃣", "9⃣", "⛽"],
    "h": ["🇭", "♓"],
    "i": ["🇮", "ℹ", "🚹", "1⃣"],
    "j": ["🇯", "🗾"],
    "k": ["🇰", "🎋"],
    "l": ["🇱", "1⃣", "🇮", "👢", "💷"],
    "m": ["🇲", "Ⓜ", "📉"],
    "n": ["🇳", "♑", "🎵"],
    "o": ["🇴", "🅾", "0⃣", "⭕", "🔘", "⏺", "⚪", "⚫", "🔵", "🔴", "💫"],
    "p": ["🇵", "🅿"],
    "q": ["🇶", "♌"],
    "r": ["🇷", "®"],
    "s": ["🇸", "💲", "5⃣", "⚡", "💰", "💵"],
    "t": ["🇹", "✝", "➕", "🎚", "🌴", "7⃣"],
    "u": ["🇺", "⛎", "🐉"],
    "v": ["🇻", "♈", "☑"],
    "w": ["🇼", "〰", "📈"],
    "x": ["🇽", "❎", "✖", "❌", "⚒"],
    "y": ["🇾", "✌", "💴"],
    "z": ["🇿", "2⃣"],
    "0": ["0⃣", "🅾", "0⃣", "⭕", "🔘", "⏺", "⚪", "⚫", "🔵", "🔴", "💫"],
    "1": ["1⃣", "🇮"],
    "2": ["2⃣", "🇿"],
    "3": ["3⃣"],
    "4": ["4⃣"],
    "5": ["5⃣", "🇸", "💲", "⚡"],
    "6": ["6⃣"],
    "7": ["7⃣"],
    "8": ["8⃣", "🎱", "🇧", "🅱"],
    "9": ["9⃣"],
    "?": ["❓"],
    "!": ["❗", "❕", "⚠", "❣"],
    # emojis that contain more than one letter can also help us react
    # letters that we are trying to replace go in front, emoji to use second
    #
    # if there is any overlap between characters that could be replaced,
    # e.g. 💯 vs 🔟, both could replace "10",
    # the longest ones & most desirable ones should go at the top
    # else you'll have "100" -> "🔟0" instead of "100" -> "💯".
    "combination": [
        ["cool", "🆒"],
        ["back", "🔙"],
        ["soon", "🔜"],
        ["free", "🆓"],
        ["end", "🔚"],
        ["top", "🔝"],
        ["abc", "🔤"],
        ["atm", "🏧"],
        ["new", "🆕"],
        ["sos", "🆘"],
        ["100", "💯"],
        ["loo", "💯"],
        ["zzz", "💤"],
        ["...", "💬"],
        ["ng", "🆖"],
        ["id", "🆔"],
        ["vs", "🆚"],
        ["wc", "🚾"],
        ["ab", "🆎"],
        ["cl", "🆑"],
        ["ok", "🆗"],
        ["up", "🆙"],
        ["10", "🔟"],
        ["11", "⏸"],
        ["ll", "⏸"],
        ["ii", "⏸"],
        ["tm", "™"],
        ["on", "🔛"],
        ["oo", "🈁"],
        ["!?", "⁉"],
        ["!!", "‼"],
        ["21", "📅"],
    ],
}
