BASE_URL = "https://statsapi.web.nhl.com"
HEADSHOT_URL = "https://nhl.bamcontent.com/images/headshots/current/168x168/{}.jpg"
CONFIG_ID = 13457745779
TEAMS = {
    "Anaheim Ducks" : {
        "away" : "#F95602",
        "conference" : "Western",
        "division" : "Pacific",
        "emoji" : "AnaheimDucks:381568940108939265",
        "home" : "#B5985A",
        "id" : 24,
        "invite" : "https://discord.gg/Pqf9W6M",
        "logo" : "https://nhl.bamcontent.com/images/photos/281720124/256x256/cut.png",
        "team_url" : "http://www.anaheimducks.com",
        "timezone" : "US/Pacific"
    },
    "Arizona Coyotes" : {
        "away" : "#E2D6B5",
        "conference" : "Western",
        "division" : "Pacific",
        "emoji" : "ArizonaCoyotes:381568940083511297",
        "home" : "#8C2633",
        "id" : 53,
        "invite" : "https://discord.gg/dguBmGm",
        "logo" : "https://nhl.bamcontent.com/images/photos/281720888/256x256/cut.png",
        "team_url" : "http://www.arizonacoyotes.com",
        "timezone" : "US/Arizona"
    },
    "Boston Bruins" : {
        "away" : "#111111",
        "conference" : "Eastern",
        "division" : "Atlantic",
        "emoji" : "BostonBruins:381568939857149954",
        "home" : "#FCB514",
        "id" : 6,
        "invite" : "https://discord.gg/BbPN25d",
        "logo" : "https://nhl.bamcontent.com/images/photos/281719378/256x256/cut.png",
        "team_url" : "https://www.youtube.com/watch?v=1RCjTRXRk1Y",
        "timezone" : "US/Eastern"
    },
    "Buffalo Sabres" : {
        "away" : "#FCB514",
        "conference" : "Eastern",
        "division" : "Atlantic",
        "emoji" : "BuffaloSabres:381568940658130944",
        "home" : "#002654",
        "id" : 7,
        "invite" : "https://discord.gg/zbDhqmt",
        "logo" : "https://nhl.bamcontent.com/images/photos/281723274/256x256/cut.png",
        "team_url" : "http://www.sabres.com",
        "timezone" : "US/Eastern"
    },
    "Calgary Flames" : {
        "away" : "#F1BE48",
        "conference" : "Western",
        "division" : "Pacific",
        "emoji" : "CalgaryFlames:381568940314460171",
        "home" : "#B72B35",
        "id" : 20,
        "invite" : "https://discord.gg/PAZsyWE",
        "logo" : "https://nhl.bamcontent.com/images/photos/281720898/256x256/cut.png",
        "team_url" : "http://www.calgaryflames.com",
        "timezone" : "US/Mountain"
    },
    "Carolina Hurricanes" : {
        "away" : "#A4A9AD",
        "conference" : "Eastern",
        "division" : "Metropolitan",
        "emoji" : "CarolinaHurricanes:381568942436646914",
        "home" : "#B72B35",
        "id" : 12,
        "invite" : "https://discord.gg/mqGDdrr",
        "logo" : "https://nhl.bamcontent.com/images/photos/281726500/256x256/cut.png",
        "team_url" : "http://www.carolinahurricanes.com",
        "timezone" : "US/Eastern"
    },
    "Chicago Blackhawks" : {
        "away" : "#000000",
        "conference" : "Western",
        "division" : "Central",
        "emoji" : "ChicagoBlackhawks:381568943279702036",
        "home" : "#CF0A2C",
        "id" : 16,
        "invite" : "https://discord.gg/DkuRmj7",
        "logo" : "https://nhl.bamcontent.com/images/photos/281726514/256x256/cut.png",
        "team_url" : "http://www.chicagoblackhawks.com",
        "timezone" : "US/Central"
    },
    "Colorado Avalanche" : {
        "away" : "#236192",
        "conference" : "Western",
        "division" : "Central",
        "emoji" : "ColoradoAvalanche:381568943170519040",
        "home" : "#6F263D",
        "id" : 21,
        "invite" : "https://discord.gg/tamwt88",
        "logo" : "https://nhl.bamcontent.com/images/photos/281721016/256x256/cut.png",
        "team_url" : "http://www.coloradoavalanche.com",
        "timezone" : "US/Mountain"
    },
    "Columbus Blue Jackets" : {
        "away" : "#CE1126",
        "conference" : "Eastern",
        "division" : "Metropolitan",
        "emoji" : "ColumbusBlueJackets:381568942839300107",
        "home" : "#041E42",
        "id" : 29,
        "invite" : "https://discord.gg/wJKdYtG",
        "logo" : "https://nhl.bamcontent.com/images/photos/281726518/256x256/cut.png",
        "team_url" : "http://www.bluejackets.com",
        "timezone" : "US/Eastern"
    },
    "Dallas Stars" : {
        "away" : "#8F8F8C",
        "conference" : "Western",
        "division" : "Central",
        "emoji" : "DallasStars:381568942520664065",
        "home" : "#006847",
        "id" : 25,
        "invite" : "https://discord.gg/KzxfCH4",
        "logo" : "https://nhl.bamcontent.com/images/photos/281726660/256x256/cut.png",
        "team_url" : "http://www.dallasstars.com",
        "timezone" : "US/Central"
    },
    "Detroit Red Wings" : {
        "away" : "#FFFFFF",
        "conference" : "Eastern",
        "division" : "Atlantic",
        "emoji" : "DetroitRedWings:381568943162130442",
        "home" : "#C8102E",
        "id" : 17,
        "invite" : "https://discord.gg/zp9WjV9",
        "logo" : "https://nhl.bamcontent.com/images/photos/281723286/256x256/cut.png",
        "team_url" : "http://www.detroitredwings.com",
        "timezone" : "US/Eastern"
    },
    "Edmonton Oilers" : {
        "away" : "#041E41",
        "conference" : "Western",
        "division" : "Pacific",
        "emoji" : "EdmontonOilers:381568942721728513",
        "home" : "#FF4C00",
        "id" : 22,
        "invite" : "https://discord.gg/6XKZyxy",
        "logo" : "https://nhl.bamcontent.com/images/photos/281721030/256x256/cut.png",
        "team_url" : "https://youtu.be/xXwkD8N8TjY?t=1m3s",
        "timezone" : "US/Mountain"
    },
    "Florida Panthers" : {
        "away" : "#041E42",
        "conference" : "Eastern",
        "division" : "Atlantic",
        "emoji" : "FloridaPanthers:381568943137095680",
        "home" : "#C8102E",
        "id" : 13,
        "invite" : "https://discord.gg/cedDpzj",
        "logo" : "https://nhl.bamcontent.com/images/photos/281723310/256x256/cut.png",
        "team_url" : "http://www.floridapanthers.com",
        "timezone" : "US/Eastern"
    },
    "Los Angeles Kings" : {
        "away" : "#B2B7BB",
        "conference" : "Western",
        "division" : "Pacific",
        "emoji" : "LosAngelesKings:381568942105296898",
        "home" : "#111111",
        "id" : 26,
        "invite" : "https://discord.gg/H6EH73h",
        "logo" : "https://nhl.bamcontent.com/images/photos/281721042/256x256/cut.png",
        "team_url" : "http://www.lakings.com",
        "timezone" : "US/Mountain"
    },
    "Minnesota Wild" : {
        "away" : "#C51230",
        "conference" : "Western",
        "division" : "Central",
        "emoji" : "MinnesotaWild:381568942596030475",
        "home" : "#004F30",
        "id" : 30,
        "invite" : "https://discord.gg/CT2HUUV",
        "logo" : "https://nhl.bamcontent.com/images/photos/281721058/256x256/cut.png",
        "team_url" : "http://www.wild.com",
        "timezone" : "US/Central"
    },
    "Montr\u00e9al Canadiens" : {
        "away" : "#192168",
        "conference" : "Eastern",
        "division" : "Atlantic",
        "emoji" : "MontrealCanadiens:381568942486847491",
        "home" : "#AF1E2D",
        "id" : 8,
        "invite" : "https://discord.gg/rhabs",
        "logo" : "https://nhl.bamcontent.com/images/photos/281723300/256x256/cut.png",
        "team_url" : "https://www.youtube.com/watch?v=9YFtlvDOVVE",
        "timezone" : "US/Eastern"
    },
    "Nashville Predators" : {
        "away" : "#041E42",
        "conference" : "Western",
        "division" : "Central",
        "emoji" : "NashvillePredators:381568942944157706",
        "home" : "#FFB81C",
        "id" : 18,
        "invite" : "https://discord.gg/Z7DF8zE",
        "logo" : "https://nhl.bamcontent.com/images/photos/281721070/256x256/cut.png",
        "team_url" : "http://www.nashvillepredators.com",
        "timezone" : "US/Central"
    },
    "New Jersey Devils" : {
        "away" : "#000000",
        "conference" : "Eastern",
        "division" : "Metropolitan",
        "emoji" : "NewJerseyDevils:381568942537179138",
        "home" : "#E03A3E",
        "id" : 1,
        "invite" : "https://discord.gg/4TtS8m4",
        "logo" : "https://nhl.bamcontent.com/images/photos/281726626/256x256/cut.png",
        "team_url" : "http://www.truesince82.com",
        "timezone" : "US/Eastern"
    },
    "New York Islanders" : {
        "away" : "#F47920",
        "conference" : "Eastern",
        "division" : "Metropolitan",
        "emoji" : "NewYorkIslanders:381568942948352011",
        "home" : "#00529B",
        "id" : 2,
        "invite" : "https://discord.gg/MSHNyqB",
        "logo" : "https://nhl.bamcontent.com/images/photos/281726632/256x256/cut.png",
        "team_url" : "http://www.newyorkislanders.com",
        "timezone" : "US/Eastern"
    },
    "New York Rangers" : {
        "away" : "#C8102E",
        "conference" : "Eastern",
        "division" : "Metropolitan",
        "emoji" : "NewYorkRangers:381568942898151435",
        "home" : "#0038A8",
        "id" : 3,
        "invite" : "https://discord.gg/zDWnpHM",
        "logo" : "https://nhl.bamcontent.com/images/photos/281718864/256x256/cut.png",
        "team_url" : "http://www.newyorkrangers.com",
        "timezone" : "US/Eastern"
    },
    "Ottawa Senators" : {
        "away" : "#CBA044",
        "conference" : "Eastern",
        "division" : "Atlantic",
        "emoji" : "OttawaSenators:381568942776254475",
        "home" : "#E31837",
        "id" : 9,
        "invite" : "https://discord.gg/VQzYRKP",
        "logo" : "https://nhl.bamcontent.com/images/photos/281723314/256x256/cut.png",
        "team_url" : "http://www.ottawasenators.com",
        "timezone" : "US/Eastern"
    },
    "Philadelphia Flyers" : {
        "away" : "#000000",
        "conference" : "Eastern",
        "division" : "Metropolitan",
        "emoji" : "PhiladelphiaFlyers:381568942004764673",
        "home" : "#F74902",
        "id" : 4,
        "invite" : "https://discord.gg/U5PdQaA",
        "logo" : "https://nhl.bamcontent.com/images/photos/281726640/256x256/cut.png",
        "team_url" : "http://www.philadelphiaflyers.com",
        "timezone" : "US/Eastern"
    },
    "Pittsburgh Penguins" : {
        "away" : "#CFC493",
        "conference" : "Eastern",
        "division" : "Metropolitan",
        "emoji" : "PittsburghPenguins:381568942587510796",
        "home" : "#FCB514",
        "id" : 5,
        "invite" : "https://discord.gg/nZ2vuWj",
        "logo" : "https://nhl.bamcontent.com/images/photos/281726648/256x256/cut.png",
        "team_url" : "https://www.youtube.com/watch?v=lDw7GqD_xro",
        "timezone" : "US/Eastern"
    },
    "San Jose Sharks" : {
        "away" : "#EA7200",
        "conference" : "Western",
        "division" : "Pacific",
        "emoji" : "SanJoseSharks:381568942864334848",
        "home" : "#006D75",
        "id" : 28,
        "invite" : "https://discord.gg/X9Xr8Zn",
        "logo" : "https://nhl.bamcontent.com/images/photos/281721090/256x256/cut.png",
        "team_url" : "http://www.sjsharks.com",
        "timezone" : "US/Pacific"
    },
    "St. Louis Blues" : {
        "away" : "#FCB514",
        "conference" : "Western",
        "division" : "Central",
        "emoji" : "StLouisBlues:381568942474526724",
        "home" : "#002F87",
        "id" : 19,
        "invite" : "https://discord.gg/013pcvc9v5MCl64Ic",
        "logo" : "https://nhl.bamcontent.com/images/photos/281752302/256x256/cut.png",
        "team_url" : "http://www.stlouisblues.com",
        "timezone" : "US/Central"
    },
    "Tampa Bay Lightning" : {
        "away" : "#FFFFFF",
        "conference" : "Eastern",
        "division" : "Atlantic",
        "emoji" : "TampaBayLightning:381568942054834196",
        "home" : "#002868",
        "id" : 14,
        "invite" : "https://discord.gg/PZ3bDJA",
        "logo" : "https://nhl.bamcontent.com/images/photos/281723320/256x256/cut.png",
        "team_url" : "https://www.youtube.com/watch?v=UjbdFKsHD_M",
        "timezone" : "US/Eastern"
    },
    "Team Atlantic" : {
        "away" : "#fef5aa",
        "conference" : "",
        "division" : "",
        "emoji" : "Atlantic:406575132895739924",
        "home" : "#032c88",
        "id" : 87,
        "invite" : "",
        "logo" : "https://i.imgur.com/I1NWsss.png",
        "team_url" : "http://nhl.coms.com",
        "timezone" : "US/Eastern"
    },
    "Team Central" : {
        "away" : "#111111",
        "conference" : "",
        "division" : "",
        "emoji" : "Central:406575132656533516",
        "home" : "#ff6668",
        "id" : 89,
        "invite" : "",
        "logo" : "https://i.imgur.com/Adrh7aD.png",
        "team_url" : "http://nhl.coms.com",
        "timezone" : "US/Central"
    },
    "Team Metropolitan" : {
        "away" : "#d1cad2",
        "conference" : "",
        "division" : "",
        "emoji" : "Metropolitan:406575133113712640",
        "home" : "#f6e98b",
        "id" : 88,
        "invite" : "",
        "logo" : "https://i.imgur.com/l4nxmZx.png",
        "team_url" : "http://nhl.coms.com",
        "timezone" : "US/Mountain"
    },
    "Team Pacific" : {
        "away" : "#FFFFFF",
        "conference" : "",
        "division" : "",
        "emoji" : "Pacific:406575133096935437",
        "home" : "#ff2734",
        "id" : 90,
        "invite" : "",
        "logo" : "https://i.imgur.com/e5a4y36.png",
        "team_url" : "http://nhl.coms.com",
        "timezone" : "US/Pacific"
    },
    "Toronto Maple Leafs" : {
        "away" : "#FFFFFF",
        "conference" : "Eastern",
        "division" : "Atlantic",
        "emoji" : "TorontoMapleLeafs:381568943011135488",
        "home" : "#003E7E",
        "id" : 10,
        "invite" : "https://discord.gg/VwDTAhk",
        "logo" : "https://nhl.bamcontent.com/images/photos/281723324/256x256/cut.png",
        "team_url" : "http://www.mapleleafs.com",
        "timezone" : "US/Eastern"
    },
    "Vancouver Canucks" : {
        "away" : "#008852",
        "conference" : "Western",
        "division" : "Pacific",
        "emoji" : "VancouverCanucks:381568942914928641",
        "home" : "#001F5C",
        "id" : 23,
        "invite" : "https://discord.gg/UTZ5Vrb",
        "logo" : "https://nhl.bamcontent.com/images/photos/281721212/256x256/cut.png",
        "team_url" : "http://www.canucks.com",
        "timezone" : "US/Pacific"
    },
    "Vegas Golden Knights" : {
        "away" : "#333F42",
        "conference" : "Western",
        "division" : "Pacific",
        "emoji" : "VegasGoldenKnights:381568942465875970",
        "home" : "#B4975A",
        "id" : 54,
        "invite" : "https://discord.gg/dMKq7RH",
        "logo" : "https://nhl.bamcontent.com/images/photos/284409696/256x256/cut.png",
        "team_url" : "https://www.youtube.com/watch?v=QrctmCqhq6o",
        "timezone" : "US/Pacific"
    },
    "Washington Capitals" : {
        "away" : "#CF0A2C",
        "conference" : "Eastern",
        "division" : "Metropolitan",
        "emoji" : "WashingtonCapitals:381568942541373440",
        "home" : "#041E41",
        "id" : 15,
        "invite" : "https://discord.gg/CbjPuTM",
        "logo" : "https://nhl.bamcontent.com/images/photos/281726654/256x256/cut.png",
        "team_url" : "http://www.washingtoncapitals.com",
        "timezone" : "US/Eastern"
    },
    "Winnipeg Jets" : {
        "away" : "#AC162C",
        "conference" : "Western",
        "division" : "Central",
        "emoji" : "WinnipegJets:381568942700888065",
        "home" : "#041E41",
        "id" : 52,
        "invite" : "https://discord.gg/tbyU5KF",
        "logo" : "https://nhl.bamcontent.com/images/photos/281723512/256x256/cut.png",
        "team_url" : "https://www.youtube.com/watch?v=jJnj0-aX_es",
        "timezone" : "US/Central"
    }
}