BASE_URL = "https://statsapi.web.nhl.com"
HEADSHOT_URL = "https://cms.nhl.bamgrid.com/images/headshots/current/168x168/{}.jpg"
CONTENT_URL = "http://statsapi.web.nhl.com/api/v1/game/{}/content"
CONFIG_ID = 13457745779
TEAMS = {
    "Anaheim Ducks": {
        "away": "#F95602",
        "conference": "Western",
        "division": "Pacific",
        "emoji": "AnaheimDucks:664662835044810772",
        "home": "#B5985A",
        "id": 24,
        "invite": "https://discord.gg/Pqf9W6M",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281720124/256x256/cut.png",
        "team_url": "https://www.nhl.com/ducks",
        "timezone": "US/Pacific",
        "nickname": ["ducks"],
        "tri_code": "ANA",
        "active": True,
    },
    "Arizona Coyotes": {
        "away": "#E2D6B5",
        "conference": "Western",
        "division": "Central",
        "emoji": "ArizonaCoyotes:897522654561583155",
        "home": "#8C2633",
        "id": 53,
        "invite": "https://discord.gg/ebGC7rP",
        "logo": "https://i.imgur.com/E0Vtt2E.png",
        "team_url": "https://www.nhl.com/coyotes",
        "timezone": "US/Arizona",
        "nickname": ["yotes"],
        "tri_code": "ARI",
        "active": True,
    },
    "Boston Bruins": {
        "away": "#111111",
        "conference": "Eastern",
        "division": "Atlantic",
        "emoji": "BostonBruins:664662840719966211",
        "home": "#FCB514",
        "id": 6,
        "invite": "https://discord.gg/BbPN25d",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281719378/256x256/cut.png",
        "team_url": "https://www.nhl.com/bruins",
        "timezone": "US/Eastern",
        "nickname": ["bruins"],
        "tri_code": "BOS",
        "active": True,
    },
    "Buffalo Sabres": {
        "away": "#FCB514",
        "conference": "Eastern",
        "division": "Atlantic",
        "emoji": "BuffaloSabres:664662843672756224",
        "home": "#002654",
        "id": 7,
        "invite": "https://discord.gg/NfAhvVnWX9",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281723274/256x256/cut.png",
        "team_url": "https://www.nhl.com/sabres",
        "timezone": "US/Eastern",
        "nickname": ["sabres"],
        "tri_code": "BUF",
        "active": True,
    },
    "Calgary Flames": {
        "away": "#F1BE48",
        "conference": "Western",
        "division": "Pacific",
        "emoji": "CalgaryFlames:664662846638129162",
        "home": "#B72B35",
        "id": 20,
        "invite": "https://discord.gg/dRQqc2h",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281720898/256x256/cut.png",
        "team_url": "https://www.nhl.com/flames",
        "timezone": "US/Mountain",
        "nickname": ["flames"],
        "tri_code": "CGY",
        "active": True,
    },
    "Carolina Hurricanes": {
        "away": "#A4A9AD",
        "conference": "Eastern",
        "division": "Metropolitan",
        "emoji": "CarolinaHurricanes:664662849058242577",
        "home": "#B72B35",
        "id": 12,
        "invite": "https://discord.gg/mqGDdrr",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281726500/256x256/cut.png",
        "team_url": "https://www.nhl.com/hurricanes",
        "timezone": "US/Eastern",
        "nickname": ["canes"],
        "tri_code": "CAR",
        "active": True,
    },
    "Chicago Blackhawks": {
        "away": "#000000",
        "conference": "Western",
        "division": "Central",
        "emoji": "ChicagoBlackhawks:664662852572938270",
        "home": "#CF0A2C",
        "id": 16,
        "invite": "https://discord.gg/WbXXanjz23",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281726514/256x256/cut.png",
        "team_url": "https://www.nhl.com/blackhawks",
        "timezone": "US/Central",
        "nickname": ["hawks"],
        "tri_code": "CHI",
        "active": True,
    },
    "Colorado Avalanche": {
        "away": "#236192",
        "conference": "Western",
        "division": "Central",
        "emoji": "ColoradoAvalanche:664662856507064330",
        "home": "#6F263D",
        "id": 21,
        "invite": "https://discord.gg/HzvKebH",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281721016/256x256/cut.png",
        "team_url": "https://www.nhl.com/avalanche",
        "timezone": "US/Mountain",
        "nickname": ["avs"],
        "tri_code": "COL",
        "active": True,
    },
    "Columbus Blue Jackets": {
        "away": "#CE1126",
        "conference": "Eastern",
        "division": "Metropolitan",
        "emoji": "ColumbusBlueJackets:664662860088999936",
        "home": "#041E42",
        "id": 29,
        "invite": "https://discord.gg/wJKdYtG",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281726518/256x256/cut.png",
        "team_url": "https://www.nhl.com/bluejackets",
        "timezone": "US/Eastern",
        "nickname": ["jackets", "bjs"],
        "tri_code": "CBJ",
        "active": True,
    },
    "Dallas Stars": {
        "away": "#8F8F8C",
        "conference": "Western",
        "division": "Central",
        "emoji": "DallasStars:664662863348105226",
        "home": "#006847",
        "id": 25,
        "invite": "https://discord.gg/uNdH6hX",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281726660/256x256/cut.png",
        "team_url": "https://www.nhl.com/stars",
        "timezone": "US/Central",
        "nickname": ["stars"],
        "tri_code": "DAL",
        "active": True,
    },
    "Detroit Red Wings": {
        "away": "#FFFFFF",
        "conference": "Eastern",
        "division": "Atlantic",
        "emoji": "DetroitRedWings:664662866359484436",
        "home": "#C8102E",
        "id": 17,
        "invite": "https://discord.gg/zp9WjV9",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281723286/256x256/cut.png",
        "team_url": "https://www.nhl.com/redwings",
        "timezone": "US/Eastern",
        "nickname": ["red wings"],
        "tri_code": "DET",
        "active": True,
    },
    "Edmonton Oilers": {
        "away": "#041E41",
        "conference": "Western",
        "division": "Pacific",
        "emoji": "EdmontonOilers:664662869291302952",
        "home": "#FF4C00",
        "id": 22,
        "invite": "https://discord.gg/6XKZyxy",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281721030/256x256/cut.png",
        "team_url": "https://www.nhl.com/oilers",
        "timezone": "US/Mountain",
        "nickname": ["oilers"],
        "tri_code": "EDM",
        "active": True,
    },
    "Florida Panthers": {
        "away": "#041E42",
        "conference": "Eastern",
        "division": "Atlantic",
        "emoji": "FloridaPanthers:664662872294555648",
        "home": "#C8102E",
        "id": 13,
        "invite": "https://discord.gg/Sn9NUqxpc6",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281723310/256x256/cut.png",
        "team_url": "https://www.nhl.com/panthers",
        "timezone": "US/Eastern",
        "nickname": ["panthers"],
        "tri_code": "FLA",
        "active": True,
    },
    "Los Angeles Kings": {
        "away": "#B2B7BB",
        "conference": "Western",
        "division": "Pacific",
        "emoji": "LosAngelesKings:664662877700882434",
        "home": "#111111",
        "id": 26,
        "invite": "https://discord.gg/H6EH73h",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281721042/256x256/cut.png",
        "team_url": "https://www.nhl.com/kings",
        "timezone": "US/Pacific",
        "nickname": ["kings"],
        "tri_code": "LAK",
        "active": True,
    },
    "Minnesota Wild": {
        "away": "#C51230",
        "conference": "Western",
        "division": "Central",
        "emoji": "MinnesotaWild:664662881668956190",
        "home": "#004F30",
        "id": 30,
        "invite": "https://discord.gg/CT2HUUV",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281721058/256x256/cut.png",
        "team_url": "https://www.nhl.com/wild",
        "timezone": "US/Central",
        "nickname": ["wild"],
        "tri_code": "MIN",
        "active": True,
    },
    "Montr\u00e9al Canadiens": {
        "away": "#192168",
        "conference": "Eastern",
        "division": "Atlantic",
        "emoji": "MontrealCanadiens:664662884852170772",
        "home": "#AF1E2D",
        "id": 8,
        "invite": "https://discord.gg/rhabs",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281723300/256x256/cut.png",
        "team_url": "https://www.nhl.com/canadiens",
        "timezone": "US/Eastern",
        "nickname": ["montreal canadiens", "habs", "montreal"],
        "tri_code": "MTL",
        "active": True,
    },
    "Nashville Predators": {
        "away": "#041E42",
        "conference": "Western",
        "division": "Central",
        "emoji": "NashvillePredators:664662887985315874",
        "home": "#FFB81C",
        "id": 18,
        "invite": "https://discord.gg/xazxsSC",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281721070/256x256/cut.png",
        "team_url": "https://www.nhl.com/predators",
        "timezone": "US/Central",
        "nickname": ["preds"],
        "tri_code": "NSH",
        "active": True,
    },
    "New Jersey Devils": {
        "away": "#000000",
        "conference": "Eastern",
        "division": "Metropolitan",
        "emoji": "NewJerseyDevils:664662891370119189",
        "home": "#E03A3E",
        "id": 1,
        "invite": "https://discord.gg/njdevils",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281726626/256x256/cut.png",
        "team_url": "https://www.nhl.com/devils",
        "timezone": "US/Eastern",
        "nickname": ["devils"],
        "tri_code": "NJD",
        "active": True,
    },
    "New York Islanders": {
        "away": "#F47920",
        "conference": "Eastern",
        "division": "Metropolitan",
        "emoji": "NewYorkIslanders:664662894847459328",
        "home": "#00529B",
        "id": 2,
        "invite": "https://discord.gg/MSHNyqB",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281726632/256x256/cut.png",
        "team_url": "https://www.nhl.com/islanders",
        "timezone": "US/Eastern",
        "nickname": ["isles"],
        "tri_code": "NYI",
        "active": True,
    },
    "New York Rangers": {
        "away": "#C8102E",
        "conference": "Eastern",
        "division": "Metropolitan",
        "emoji": "NewYorkRangers:664662897799987240",
        "home": "#0038A8",
        "id": 3,
        "invite": "https://discord.gg/rrjvywb",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281718864/256x256/cut.png",
        "team_url": "https://www.nhl.com/nyrangers",
        "timezone": "US/Eastern",
        "nickname": ["rangers"],
        "tri_code": "NYR",
        "active": True,
    },
    "Ottawa Senators": {
        "away": "#CBA044",
        "conference": "Eastern",
        "division": "Atlantic",
        "emoji": "OttawaSenators:897522793254625391",
        "home": "#E31837",
        "id": 9,
        "invite": "https://discord.gg/VQzYRKP",
        "logo": "https://i.imgur.com/RHR1YOZ.png",
        "team_url": "https://www.nhl.com/senators",
        "timezone": "US/Eastern",
        "nickname": ["sens"],
        "tri_code": "OTT",
        "active": True,
    },
    "Philadelphia Flyers": {
        "away": "#000000",
        "conference": "Eastern",
        "division": "Metropolitan",
        "emoji": "PhiladelphiaFlyers:664662903118626844",
        "home": "#F74902",
        "id": 4,
        "invite": "https://discord.gg/WwG2MFf",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281726640/256x256/cut.png",
        "team_url": "https://www.nhl.com/flyers",
        "timezone": "US/Eastern",
        "nickname": ["flyers"],
        "tri_code": "PHI",
        "active": True,
    },
    "Pittsburgh Penguins": {
        "away": "#CFC493",
        "conference": "Eastern",
        "division": "Metropolitan",
        "emoji": "PittsburghPenguins:664662906000113664",
        "home": "#FCB514",
        "id": 5,
        "invite": "https://discord.gg/FkAUtvs",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281726648/256x256/cut.png",
        "team_url": "https://www.nhl.com/penguins",
        "timezone": "US/Eastern",
        "nickname": ["pens"],
        "tri_code": "PIT",
        "active": True,
    },
    "San Jose Sharks": {
        "away": "#EA7200",
        "conference": "Western",
        "division": "Pacific",
        "emoji": "SanJoseSharks:664662909246373898",
        "home": "#006D75",
        "id": 28,
        "invite": "https://discord.gg/X9Xr8Zn",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281721090/256x256/cut.png",
        "team_url": "https://www.nhl.com/sharks",
        "timezone": "US/Pacific",
        "nickname": ["sharks"],
        "tri_code": "SJS",
        "active": True,
    },
    "Seattle Kraken": {
        "away": "#5dbcd2",
        "conference": "Western",
        "division": "Pacific",
        "emoji": "SeattleKraken:735938319883698216",
        "home": "#0C1A28",
        "id": 55,
        "invite": "https://discord.gg/ajgvaXWHBQ",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/317591200/256x256/cut.png",
        "team_url": "https://www.nhl.com/kraken",
        "timezone": "US/Pacific",
        "nickname": ["kraken"],
        "tri_code": "SEA",
        "active": True,
    },
    "St. Louis Blues": {
        "away": "#FCB514",
        "conference": "Western",
        "division": "Central",
        "emoji": "StLouisBlues:664662913000407052",
        "home": "#002F87",
        "id": 19,
        "invite": "https://discord.gg/013pcvc9v5MCl64Ic",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281752302/256x256/cut.png",
        "team_url": "https://www.nhl.com/blues",
        "timezone": "US/Central",
        "nickname": ["blues"],
        "tri_code": "STL",
        "active": True,
    },
    "Tampa Bay Lightning": {
        "away": "#FFFFFF",
        "conference": "Eastern",
        "division": "Atlantic",
        "emoji": "TampaBayLightning:664662915621584906",
        "home": "#002868",
        "id": 14,
        "invite": "https://discord.gg/WjNvprr",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281723320/256x256/cut.png",
        "team_url": "https://www.nhl.com/lightning",
        "timezone": "US/Eastern",
        "nickname": ["bolts"],
        "tri_code": "TBL",
        "active": True,
    },
    "Team Atlantic": {
        "away": "#fef5aa",
        "conference": "",
        "division": "",
        "emoji": "Atlantic:406575132895739924",
        "home": "#032c88",
        "id": 87,
        "invite": "No Server Found",
        "logo": "https://i.imgur.com/I1NWsss.png",
        "team_url": "http://nhl.coms.com",
        "timezone": "US/Eastern",
        "nickname": [],
        "tri_code": "",
        "active": False,
    },
    "Team Central": {
        "away": "#111111",
        "conference": "",
        "division": "",
        "emoji": "Central:406575132656533516",
        "home": "#ff6668",
        "id": 89,
        "invite": "No Server Found",
        "logo": "https://i.imgur.com/Adrh7aD.png",
        "team_url": "http://nhl.coms.com",
        "timezone": "US/Central",
        "nickname": [],
        "tri_code": "",
        "active": False,
    },
    "Team Metropolitan": {
        "away": "#d1cad2",
        "conference": "",
        "division": "",
        "emoji": "Metropolitan:406575133113712640",
        "home": "#f6e98b",
        "id": 88,
        "invite": "No Server Found",
        "logo": "https://i.imgur.com/l4nxmZx.png",
        "team_url": "http://nhl.coms.com",
        "timezone": "US/Mountain",
        "nickname": [],
        "tri_code": "",
        "active": False,
    },
    "Team Pacific": {
        "away": "#FFFFFF",
        "conference": "",
        "division": "",
        "emoji": "Pacific:406575133096935437",
        "home": "#ff2734",
        "id": 90,
        "invite": "No Server Found",
        "logo": "https://i.imgur.com/e5a4y36.png",
        "team_url": "http://nhl.coms.com",
        "timezone": "US/Pacific",
        "nickname": [],
        "tri_code": "",
        "active": False,
    },
    "Toronto Maple Leafs": {
        "away": "#FFFFFF",
        "conference": "Eastern",
        "division": "Atlantic",
        "emoji": "TorontoMapleLeafs:664662927739191326",
        "home": "#003E7E",
        "id": 10,
        "invite": "https://discord.gg/leafs",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281723324/256x256/cut.png",
        "team_url": "http://www.mapleleafs.com",
        "timezone": "US/Eastern",
        "nickname": ["leafs"],
        "tri_code": "TOR",
        "active": True,
    },
    "Vancouver Canucks": {
        "away": "#008852",
        "conference": "Western",
        "division": "Pacific",
        "emoji": "VancouverCanucks:664662930859753492",
        "home": "#001F5C",
        "id": 23,
        "invite": "https://discord.gg/UTZ5Vrb",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281721212/256x256/cut.png",
        "team_url": "http://www.canucks.com",
        "timezone": "US/Pacific",
        "nickname": ["canucks", "nucks", "nuks"],
        "tri_code": "VAN",
        "active": True,
    },
    "Vegas Golden Knights": {
        "away": "#333F42",
        "conference": "Western",
        "division": "Pacific",
        "emoji": "VegasGoldenKnights:664662933967601768",
        "home": "#B4975A",
        "id": 54,
        "invite": "https://discord.gg/dMKq7RH",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/284409696/256x256/cut.png",
        "team_url": "https://www.nhl.com/goldenknights",
        "timezone": "US/Pacific",
        "nickname": ["knights"],
        "tri_code": "VGK",
        "active": True,
    },
    "Washington Capitals": {
        "away": "#CF0A2C",
        "conference": "Eastern",
        "division": "Metropolitan",
        "emoji": "WashingtonCapitals:664664062180851722",
        "home": "#041E41",
        "id": 15,
        "invite": "https://discord.gg/2HXAJm23Ph",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281726654/256x256/cut.png",
        "team_url": "https://www.nhl.com/capitals",
        "timezone": "US/Eastern",
        "nickname": ["caps"],
        "tri_code": "WSH",
        "active": True,
    },
    "Winnipeg Jets": {
        "away": "#AC162C",
        "conference": "Western",
        "division": "Central",
        "emoji": "WinnipegJets:664664065112539154",
        "home": "#041E41",
        "id": 52,
        "invite": "https://discord.gg/Q7bm7ZK8QG",
        "logo": "https://cms.nhl.bamgrid.com/images/photos/281723512/256x256/cut.png",
        "team_url": "https://www.nhl.com/jets",
        "timezone": "US/Central",
        "nickname": ["jets"],
        "tri_code": "WPG",
        "active": True,
    },
    "Montreal Wanderers": {
        "conference": "",
        "division": "",
        "id": 41,
        "logo": "https://imgur.com/6ksA0hH.png",
        "tri_code": "MWN",
        "away": "#000000",
        "home": "#000000",
        "emoji": "MontrealWanderers:747413468755394600",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "St. Louis Eagles": {
        "conference": "",
        "division": "",
        "id": 45,
        "logo": "https://imgur.com/ehHaKTP.png",
        "tri_code": "SLE",
        "away": "#000000",
        "home": "#000000",
        "emoji": "StLouisEagles:747409678417526895",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Hamilton Tigers": {
        "conference": "",
        "division": "",
        "id": 37,
        "logo": "https://imgur.com/le8g7kW.png",
        "tri_code": "HAM",
        "away": "#000000",
        "home": "#000000",
        "emoji": "HamiltonTigers:747409674957094913",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Montreal Maroons": {
        "conference": "",
        "division": "",
        "id": 43,
        "logo": "https://imgur.com/LGotJwK.png",
        "tri_code": "MMR",
        "away": "#000000",
        "home": "#000000",
        "emoji": "MontrealMaroons:747409674843717712",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Brooklyn Americans": {
        "conference": "",
        "division": "",
        "id": 51,
        "logo": "https://imgur.com/b7wDd9v.png",
        "tri_code": "NYA",
        "away": "#000000",
        "home": "#000000",
        "emoji": "BrooklynAmericans:747409673447014453",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Philadelphia Quakers": {
        "conference": "",
        "division": "",
        "id": 39,
        "logo": "https://imgur.com/RIyBZmz.png",
        "tri_code": "PIR",
        "away": "#000000",
        "home": "#000000",
        "emoji": "PhiladelphiaQuakers:747409676655657081",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Cleveland Barons": {
        "conference": "",
        "division": "",
        "id": 46,
        "logo": "https://imgur.com/ummTel7.png",
        "tri_code": "OAK",
        "away": "#000000",
        "home": "#000000",
        "emoji": "ClevelandBarons:747409678308343819",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Ottawa Senators (1917)": {
        "conference": "",
        "division": "",
        "id": 36,
        "logo": "https://imgur.com/wLtNlq0.png",
        "tri_code": "SEN",
        "away": "#000000",
        "home": "#000000",
        "emoji": "OttawaSenators:747409677784055828",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Quebec Bulldogs": {
        "conference": "",
        "division": "",
        "id": 42,
        "logo": "https://imgur.com/vbxASOv.png",
        "tri_code": "QBD",
        "away": "#000000",
        "home": "#000000",
        "emoji": "QuebecBulldogs:747409675787698216",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Toronto Arenas": {
        "conference": "",
        "division": "",
        "id": 57,
        "logo": "https://imgur.com/auKTjWh.png",
        "tri_code": "TAN",
        "away": "#000000",
        "home": "#000000",
        "emoji": "TorontoArenas:747409674860494919",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Toronto St. Patricks": {
        "conference": "",
        "division": "",
        "id": 58,
        "logo": "https://imgur.com/xQp3Hqn.png",
        "tri_code": "TSP",
        "away": "#000000",
        "home": "#000000",
        "emoji": "TorontoStPatricks:747409677624803368",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "New York Americans": {
        "conference": "",
        "division": "",
        "id": 44,
        "logo": "https://imgur.com/q7YXoLM.png",
        "tri_code": "NYA",
        "away": "#000000",
        "home": "#000000",
        "emoji": "NewYorkAmericans:747409678346092654",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Pittsburgh Pirates": {
        "conference": "",
        "division": "",
        "id": 38,
        "logo": "https://imgur.com/dsFuIsp.png",
        "tri_code": "PIR",
        "away": "#000000",
        "home": "#000000",
        "emoji": "PittsburghPirates:747409678480179310",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Detroit Cougars": {
        "conference": "",
        "division": "",
        "id": 40,
        "logo": "https://imgur.com/r63YuFI.png",
        "tri_code": "DCG",
        "away": "#000000",
        "home": "#000000",
        "emoji": "DetroitCougars:747409675149901835",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Detroit Falcons": {
        "conference": "",
        "division": "",
        "id": 50,
        "logo": "https://imgur.com/WDZdGXV.png",
        "tri_code": "DFL",
        "away": "#000000",
        "home": "#000000",
        "emoji": "DetroitFalcons:747409678295629854",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Oakland Seals": {
        "conference": "",
        "division": "",
        "id": 46,
        "logo": "https://imgur.com/Qf8QS5q.png",
        "tri_code": "OAK",
        "away": "#000000",
        "home": "#000000",
        "emoji": "OaklandSeals:747409678278852608",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "California Golden Seals": {
        "conference": "",
        "division": "",
        "id": 56,
        "logo": "https://imgur.com/RFNfdkj.png",
        "tri_code": "CGS",
        "away": "#000000",
        "home": "#000000",
        "emoji": "CaliforniaGoldenSeals:747409676127436854",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Minnesota North Stars": {
        "conference": "Prince of Wales",
        "division": "Norris",
        "id": 31,
        "logo": "https://imgur.com/iaIpyke.png",
        "tri_code": "MNS",
        "away": "#000000",
        "home": "#000000",
        "emoji": "MinnesotaNorthStars:747409676462719026",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Atlanta Flames": {
        "conference": "",
        "division": "",
        "id": 47,
        "logo": "https://imgur.com/SuPIGnQ.png",
        "tri_code": "AFM",
        "away": "#000000",
        "home": "#000000",
        "emoji": "AtlantaFlames:747409673371779072",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Colorado Rockies": {
        "conference": "",
        "division": "",
        "id": 35,
        "logo": "https://imgur.com/u7099Fp.png",
        "tri_code": "CLR",
        "away": "#000000",
        "home": "#000000",
        "emoji": "ColoradoRockies:747409677394116690",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Kansas City Scouts": {
        "conference": "",
        "division": "",
        "id": 48,
        "logo": "https://imgur.com/Z05dKee.png",
        "tri_code": "KCS",
        "away": "#000000",
        "home": "#000000",
        "emoji": "KansasCityScouts:747409678773911602",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Hartford Whalers": {
        "conference": "Prince of Wales",
        "division": "Adams",
        "id": 34,
        "logo": "https://imgur.com/HEhXCdm.png",
        "tri_code": "HFD",
        "away": "#000000",
        "home": "#000000",
        "emoji": "HartfordWhalers:747409677339459595",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Quebec Nordiques": {
        "conference": "Prince of Wales",
        "division": "Adams",
        "id": 32,
        "logo": "https://imgur.com/i6sMDMv.png",
        "tri_code": "QUE",
        "away": "#000000",
        "home": "#000000",
        "emoji": "QuebecNordiques:747409676898926642",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Phoenix Coyotes": {
        "conference": "Western",
        "division": "Pacific",
        "id": 27,
        "logo": "https://imgur.com/FIxCOnj.png",
        "tri_code": "PHX",
        "away": "#000000",
        "home": "#000000",
        "emoji": "PhoenixCoyotes:747409679193341952",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Winnipeg Jets (1979)": {
        "conference": "Clarence Campbell",
        "division": "Smythe",
        "id": 33,
        "logo": "https://imgur.com/otWBB2N.png",
        "tri_code": "WIN",
        "away": "#000000",
        "home": "#000000",
        "emoji": "WinnipegJets:747409678304280637",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Atlanta Thrashers": {
        "conference": "",
        "division": "",
        "id": 11,
        "logo": "https://imgur.com/7jYCLTD.png",
        "tri_code": "ATL",
        "away": "#000000",
        "home": "#000000",
        "emoji": "AtlantaThrashers:747409677247315987",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Team Honda West": {
        "conference": "",
        "division": "Honda West",
        "id": 11,
        "logo": "https://cdn.discordapp.com/attachments/440178442886053888/796832213060550686/9110__national_hockey_league-division-2021.png",
        "tri_code": "THW",
        "away": "#000000",
        "home": "#000000",
        "emoji": "",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Team MassMutual East": {
        "conference": "",
        "division": "MassMutual East",
        "id": 11,
        "logo": "https://cdn.discordapp.com/attachments/440178442886053888/796832177836785684/9017__national_hockey_league-division-2021.png",
        "tri_code": "THW",
        "away": "#000000",
        "home": "#000000",
        "emoji": "",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Team Scotia North": {
        "conference": "",
        "division": "Scotia North",
        "id": 11,
        "logo": "https://cdn.discordapp.com/attachments/440178442886053888/796832087733960765/1380__national_hockey_league-division-2021.png",
        "tri_code": "THW",
        "away": "#000000",
        "home": "#000000",
        "emoji": "",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
    "Team Discover Central": {
        "conference": "",
        "division": "Discover Central",
        "id": 11,
        "logo": "https://cdn.discordapp.com/attachments/440178442886053888/796832145779720242/3662__national_hockey_league-division-2021.png",
        "tri_code": "THW",
        "away": "#000000",
        "home": "#000000",
        "emoji": "",
        "timezone": "US/Eastern",
        "team_url": "",
        "nickname": [],
        "invite": "No Server Found",
        "active": False,
    },
}
SLASH_COMMANDS = {
    "name": "hockey",
    "description": "Hockey commnads",
    "options": [
        {
            "name": "games",
            "description": "Current and upcoming NHL games",
            "type": 1,
            "options": [
                {
                    "name": "team",
                    "type": 3,
                    "description": ".",
                    "required": False,
                    "autocomplete": True,
                },
                {
                    "name": "date",
                    "type": 3,
                    "description": "YYYY-MM-DD formatted",
                    "required": False,
                },
            ],
        },
        {
            "name": "heatmap",
            "description": "Get game heatmaps",
            "type": 1,
            "options": [
                {
                    "name": "team",
                    "type": 3,
                    "description": ".",
                    "required": False,
                    "autocomplete": True,
                },
                {
                    "name": "date",
                    "type": 3,
                    "description": "YYYY-MM-DD formatted",
                    "required": False,
                },
                {
                    "name": "style",
                    "type": 3,
                    "description": ".",
                    "required": False,
                    "choices": [
                        {"name": "All", "value": "all"},
                        {"name": "EV", "value": "ev"},
                        {"name": "5v5", "value": "5v5"},
                        {"name": "SVA", "value": "sva"},
                        {"name": "Home 5v4", "value": "home5v4"},
                        {"name": "Away 5v4", "value": "away5v4"}
                    ]
                },
            ],
        },
        {
            "name": "gameflow",
            "description": "Show gameflow for a game",
            "type": 1,
            "options": [
                {
                    "name": "team",
                    "type": 3,
                    "description": ".",
                    "required": False,
                    "autocomplete": True,
                },
                {
                    "name": "date",
                    "type": 3,
                    "description": "YYYY-MM-DD formatted",
                    "required": False,
                },
                {
                    "name": "corsi",
                    "type": 5,
                    "description": ".",
                    "required": False,
                },
                {
                    "name": "strength",
                    "type": 3,
                    "description": ".",
                    "required": False,
                    "choices": [
                        {"name": "All", "value": "all"},
                        {"name": "EV", "value": "ev"},
                        {"name": "5v5", "value": "5v5"},
                        {"name": "SVA", "value": "sva"}
                    ]
                },
            ],
        },
        {
            "name": "schedule",
            "description": "Show the current NHL Schedule",
            "type": 1,
            "options": [
                {
                    "name": "team",
                    "type": 3,
                    "description": ".",
                    "required": False,
                    "autocomplete": True,
                },
                {
                    "name": "date",
                    "type": 3,
                    "description": "YYYY-MM-DD formatted",
                    "required": False,
                },
            ],
        },
        {
            "name": "player",
            "description": "Show stats and information about any NHL Player",
            "type": 1,
            "options": [
                {
                    "name": "search",
                    "type": 3,
                    "description": "The name of the player to search for",
                    "required": True,
                    "autocomplete": True,
                }
            ],
        },
        {
            "name": "roster",
            "description": "Show a team Roster for a specific year",
            "type": 1,
            "options": [
                {
                    "name": "search",
                    "type": 3,
                    "description": "The teams roster to look for",
                    "required": True,
                    "autocomplete": True,
                },
                {
                    "name": "season",
                    "type": 3,
                    "description": "The season roster to search for must be YYYY or YYYYYYYY.",
                    "required": False,
                },
            ],
        },
        {
            "name": "leaderboard",
            "description": "Show the server Pickems leaderboard",
            "type": 1,
            "options": [
                {
                    "name": "leaderboard_type",
                    "type": 3,
                    "description": "Must be either seasonal, weekly, or worst.",
                    "required": False,
                    "choices": [
                        {"name": "Seasonal", "value": "seasonal"},
                        {"name": "Weekly", "value": "weekly"},
                        {"name": "Playoffs", "value": "playoffs"},
                        {"name": "Weekly Playoffs", "value": "playoffs_weekly"},
                        {"name": "Pre-Season", "value": "pre-season"},
                        {"name": "Weekly Pre-Season", "value": "pre-season_weekly"},
                        {"name": "Worst", "value": "worst"},
                    ],
                }
            ],
        },
        {
            "name": "standings",
            "description": "Show the current NHL Standings",
            "type": 1,
            "options": [
                {
                    "name": "search",
                    "type": 3,
                    "description": "All, conference, or division.",
                    "required": True,
                    "choices": [
                        {"name": "All", "value": "all"},
                        {"name": "Metropolitan", "value": "metropolitan"},
                        {"name": "Atlantic", "value": "atlantic"},
                        {"name": "Central", "value": "central"},
                        {"name": "Pacific", "value": "pacific"},
                        {"name": "Eastern", "value": "eastern"},
                        {"name": "Western", "value": "western"},
                    ],
                }
            ],
        },
        {
            "name": "otherdiscords",
            "description": "Get a team specific discord invite",
            "type": 1,
            "options": [
                {
                    "name": "team",
                    "type": 3,
                    "description": "The team server invite you want.",
                    "required": True,
                    "autocomplete": True,
                }
            ],
        },
        {
            "name": "pickems",
            "description": "Manage Hockey Pickems settings",
            "type": 2,
            "options": [
                {
                    "name": "settings",
                    "type": 1,
                    "description": "Show this servers current pickems settings.",
                },
                {
                    "name": "votes",
                    "description": "Show your current votes on pickems in this server.",
                    "type": 1,
                },
                {
                    "name": "basecredits",
                    "type": 1,
                    "description": "Set the base rewards credits for pickems.",
                    "options": [
                        {
                            "name": "amount",
                            "type": 4,
                            "required": True,
                            "description": "Number of base credits to award.",
                        }
                    ],
                },
                {
                    "name": "topcredits",
                    "type": 1,
                    "description": "Set the amount of credits awarded to the top x winners of pickems.",
                    "options": [
                        {
                            "name": "amount",
                            "type": 4,
                            "required": True,
                            "description": "Number of top credits to award.",
                        }
                    ],
                },
                {
                    "name": "winners",
                    "type": 1,
                    "description": "Set how many top winners to revieve the weekly reward.",
                    "options": [
                        {
                            "name": "amount",
                            "type": 4,
                            "required": True,
                            "description": "Number of top winners to receive weekly reward.",
                        }
                    ],
                },
                {
                    "name": "message",
                    "type": 1,
                    "description": "Set a custom message for each pickems page.",
                    "options": [
                        {
                            "name": "message",
                            "type": 3,
                            "required": False,
                            "description": "The message that is posted at the start of all pickems threads.",
                        }
                    ],
                },
                {
                    "name": "setup",
                    "type": 1,
                    "description": "Setup pickems on this server.",
                    "options": [
                        {
                            "name": "channel",
                            "type": 7,
                            "required": True,
                            "description": "The channel that pickems threads will be created in.",
                        }
                    ],
                },
                {
                    "name": "clear",
                    "type": 1,
                    "description": "Stop posting new pickems threads and clear existing pickems threads.",
                },
                {
                    "name": "page",
                    "type": 1,
                    "description": "Setup a single days pickems information in the current channel.",
                    "options": [
                        {
                            "name": "date",
                            "type": 3,
                            "required": True,
                            "description": "Must be formatted like YYYY-MM-DD",
                        }
                    ],
                },
            ],
        },
        {
            "name": "gdt",
            "description": "Manage Hockey Game Day Threads",
            "type": 2,
            "options": [
                {
                    "name": "settings",
                    "type": 1,
                    "description": "Show this servers current GDT settings.",
                },
                {
                    "name": "delete",
                    "type": 1,
                    "description": "Delete all current game day threads for this server",
                },
                {
                    "name": "defaultstate",
                    "type": 1,
                    "description": "Set specific state updates to use for game day threads",
                    "options": [
                        {
                            "name": "state",
                            "type": 3,
                            "required": True,
                            "description": "The state you want to add/remove from game day threads.",
                            "choices": [
                                {"name": "Game Previews", "value": "Preview"},
                                {"name": "Live", "value": "Live"},
                                {"name": "Final", "value": "Final"},
                                {"name": "Goals", "value": "Goal"},
                                {"name": "Period Recaps", "value": "Periodrecap"},
                            ],
                        }
                    ],
                },
                {
                    "name": "create",
                    "type": 1,
                    "description": "Creates the next GDT for the server.",
                },
                {
                    "name": "toggle",
                    "type": 1,
                    "description": "Toggle creating new Game Day Threads.",
                },
                {
                    "name": "channel",
                    "type": 1,
                    "description": "Change the channel used for Game Day Threads.",
                    "options": [
                        {
                            "name": "channel",
                            "type": 7,
                            "required": True,
                            "description": "The channel that Game Day Threads will be created in.",
                        }
                    ],
                },
                {
                    "name": "update",
                    "type": 1,
                    "description": "Edit starting game day thread message.",
                    "options": [
                        {
                            "name": "update_start",
                            "type": 5,
                            "required": True,
                            "description": ".",
                        }
                    ],
                },
                {
                    "name": "setup",
                    "type": 1,
                    "description": "Setup game day threads for a single team or all teams.",
                    "options": [
                        {
                            "name": "team",
                            "type": 3,
                            "required": True,
                            "description": "The team you want to setup Game Day Threads for.",
                            "autocomplete": True,
                        },
                        {
                            "name": "channel",
                            "type": 7,
                            "required": False,
                            "description": "The channel that Game Day Threads will be created in.",
                        },
                    ],
                },
            ],
        },
        {
            "name": "set",
            "description": "Setup goal updates, standings, etc.",
            "type": 2,
            "options": [
                {
                    "name": "settings",
                    "type": 1,
                    "description": "Show the current server hockey settings.",
                    "required": False,
                },
                {
                    "name": "poststandings",
                    "type": 1,
                    "description": "Setup automatic standings.",
                    "options": [
                        {
                            "name": "standings_type",
                            "description": "The type of standings you want to show.",
                            "type": 3,
                            "required": True,
                            "choices": [
                                {"name": "All", "value": "all"},
                                {"name": "Metropolitan", "value": "metropolitan"},
                                {"name": "Atlantic", "value": "atlantic"},
                                {"name": "Central", "value": "central"},
                                {"name": "Pacific", "value": "pacific"},
                                {"name": "Eastern", "value": "eastern"},
                                {"name": "Western", "value": "western"},
                            ],
                        },
                        {
                            "name": "channel",
                            "description": "The channel you want to post the standings to.",
                            "type": 7,
                            "required": False,
                        },
                    ],
                },
                {
                    "name": "add",
                    "type": 1,
                    "description": "Adds NHL updates to a channel",
                    "options": [
                        {
                            "name": "team",
                            "description": "The team you want updates for. Do all for all teams.",
                            "type": 3,
                            "required": True,
                            "autocomplete": True,
                        },
                        {
                            "name": "channel",
                            "description": "The channel you want to post the standings to.",
                            "type": 7,
                            "required": False,
                        },
                    ],
                },
                {
                    "name": "remove",
                    "type": 1,
                    "description": "Removes NHL updates from a channel",
                    "options": [
                        {
                            "name": "team",
                            "description": "The team you want updates for. Do all for all teams.",
                            "type": 3,
                            "required": True,
                            "autocomplete": True,
                        },
                        {
                            "name": "channel",
                            "description": "The channel you want to post the standings to.",
                            "type": 7,
                            "required": False,
                        },
                    ],
                },
                {
                    "name": "stateupdates",
                    "type": 1,
                    "description": "Add or remove specific game updates from update channels.",
                    "options": [
                        {
                            "name": "channel",
                            "description": "The channel with game updates you want to edit.",
                            "type": 7,
                            "required": True,
                        },
                        {
                            "name": "state",
                            "description": "Set what type of game updates to be posted.",
                            "type": 3,
                            "required": False,
                            "choices": [
                                {"name": "Game Previews", "value": "Preview"},
                                {"name": "Live", "value": "Live"},
                                {"name": "Final", "value": "Final"},
                                {"name": "Goals", "value": "Goal"},
                                {"name": "Period Recaps", "value": "Periodrecap"},
                            ],
                        },
                    ],
                },
            ],
        },
    ],
}
