name: Style formatting

on: [push, pull_request]

jobs:
  mypy:
    name: Style check with Black and iSort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - run: "python -m pip install black==22.3.0 isort==5.10.1"
        name: Install dependencies
      - run: "make stylediff"
        name: Run Style Checks
